<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Parquet.Net" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Parquet.SourceGenerator.Attributes\Parquet.SourceGenerator.Attributes.csproj" />
        <ProjectReference
            Include="..\..\src\Parquet.SourceGenerator\Parquet.SourceGenerator.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
    </ItemGroup>
</Project>
