using System;
using System.Collections.Generic;
using System.Text;
using Parquet.SourceGenerator.Emitter.Components;
using Parquet.SourceGenerator.Models;

namespace Parquet.SourceGenerator.Emitter.Arrow;

/// <summary>
/// Emits the read half of the Apache Arrow bridge (#178): a <c>{Type}.Arrow.g.cs</c> partial adding
/// <c>ReadParquetRecordBatchesAsync</c> to the generated extensions class.
/// </summary>
/// <remarks>
/// <para>
/// The partial only exists when the consumer compilation references Apache.Arrow — see
/// <see cref="ArrowMappingComponent.GateTypeMetadataName"/>. Everything Arrow-typed lives in this
/// file, so a consumer without the reference gets byte-identical output to before the bridge
/// existed and inherits no Arrow dependency.
/// </para>
/// <para>
/// Column data comes off the same <c>ArrayPool</c> rentals the POCO read path uses: one row group is
/// decoded into rented buffers, and each buffer is copied into Arrow-owned buffers. Copying is
/// deliberate (the rentals are returned as soon as the row group is done, so Arrow cannot borrow
/// them), and no POCO is ever constructed on this path.
/// </para>
/// </remarks>
internal static class ArrowBridgeEmitter
{
    /// <summary>
    /// Emits the Arrow partial for a model, or returns null when the model cannot cross the bridge
    /// (nested members, or a leaf with no Arrow mapping).
    /// </summary>
    public static string? EmitSource(TargetClassModel model)
    {
        if (!ArrowMappingComponent.IsExportable(model))
            return null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine(
            "#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629"
        );
        builder.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }

        string extensionsClassName =
            $"{model.ClassName.Replace(".", string.Empty)}ParquetExtensions";

        builder.AppendLine($"public static partial class {extensionsClassName}");
        builder.AppendLine("{");

        EmitArrowSchema(builder, model);
        builder.AppendLine();
        EmitTypeHelpers(builder, model);
        EmitReadRecordBatchesAsync(builder, model);
        builder.AppendLine();
        EmitColumnBuilders(builder, model);

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IEnumerable<(int Index, PropertyModel Prop, ArrowMapping Map)> Columns(
        TargetClassModel model
    )
    {
        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            yield return (i, prop, ArrowMappingComponent.MapOrThrow(prop));
        }
    }

    // ──────────────────────────────────────────────────────────
    //  SCHEMA
    // ──────────────────────────────────────────────────────────

    private static void EmitArrowSchema(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    private static global::Apache.Arrow.Schema? _arrowSchema;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// The Arrow schema <c>{model.ClassName}</c> exports as, derived from the generated"
        );
        builder.AppendLine("    /// <see cref=\"Schema\"/> through the shared mapping table.");
        builder.AppendLine("    /// </summary>");
        builder.Append(
            "    public static global::Apache.Arrow.Schema ArrowSchema => _arrowSchema ??= BuildArrowSchema("
        );
        for (int i = 0; i < model.Properties.Length; i++)
        {
            builder.Append(i == 0 ? "" : ", ");
            builder.Append($"_field_{i}");
        }
        builder.AppendLine(");");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            "    /// Builds the Arrow schema from resolved <c>DataField</c>s, so decimal precision/scale and"
        );
        builder.AppendLine(
            "    /// timestamp unit come from the schema actually in play rather than a compile-time guess."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    private static global::Apache.Arrow.Schema BuildArrowSchema(");
        for (int i = 0; i < model.Properties.Length; i++)
        {
            string comma = i == model.Properties.Length - 1 ? ")" : ",";
            builder.AppendLine($"        global::Parquet.Schema.DataField field_{i}{comma}");
        }
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var fields = new global::Apache.Arrow.Field[{model.Properties.Length}];"
        );
        foreach ((int i, PropertyModel prop, ArrowMapping map) in Columns(model))
        {
            string name = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
                prop.ParquetColumnName,
                quote: true
            );
            string typeExpr = ArrowMappingComponent.ArrowTypeExpression(map, $"field_{i}");
            string nullable = prop.IsNullable ? "true" : "false";
            builder.AppendLine(
                $"        fields[{i}] = new global::Apache.Arrow.Field({name}, {typeExpr}, {nullable});"
            );
        }
        builder.AppendLine(
            "        return new global::Apache.Arrow.Schema(fields, metadata: null);"
        );
        builder.AppendLine("    }");
    }

    // ──────────────────────────────────────────────────────────
    //  TYPE + CONVERSION HELPERS (emitted only when a column needs them)
    // ──────────────────────────────────────────────────────────

    private static void EmitTypeHelpers(StringBuilder builder, TargetClassModel model)
    {
        bool hasDecimal = false;
        bool hasTimestamp = false;
        bool hasTime = false;
        bool hasDate = false;
        bool hasGuid = false;
        foreach ((int _, PropertyModel _, ArrowMapping map) in Columns(model))
        {
            hasDecimal |= map == ArrowMapping.Decimal128;
            hasTimestamp |= map == ArrowMapping.Timestamp;
            hasTime |= map == ArrowMapping.Time64;
            hasDate |= map == ArrowMapping.Date32;
            hasGuid |= map == ArrowMapping.FixedSizeBinary16;
        }

        if (hasDecimal)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Decimal precision and scale come off the resolved field; a plain DataField (a file that"
            );
            builder.AppendLine(
                "    /// omitted the annotation) falls back to the generator's 38/18 default."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static global::Apache.Arrow.Types.Decimal128Type ArrowDecimalType(global::Parquet.Schema.DataField field)"
            );
            builder.AppendLine("    {");
            builder.AppendLine(
                "        return field is global::Parquet.Schema.DecimalDataField dec"
            );
            builder.AppendLine(
                "            ? new global::Apache.Arrow.Types.Decimal128Type(dec.Precision, dec.Scale)"
            );
            builder.AppendLine(
                "            : new global::Apache.Arrow.Types.Decimal128Type(38, 18);"
            );
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        if (hasTimestamp)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Timestamp unit mirrors the Parquet annotation. Impala int96 carries nanosecond width but"
            );
            builder.AppendLine(
                "    /// Parquet.Net hands back <c>DateTime</c> (100ns ticks), so it exports as microseconds."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static global::Apache.Arrow.Types.TimestampType ArrowTimestampType(global::Parquet.Schema.DataField field)"
            );
            builder.AppendLine("    {");
            builder.AppendLine(
                "        var unit = global::Apache.Arrow.Types.TimeUnit.Microsecond;"
            );
            builder.AppendLine("        if (field is global::Parquet.Schema.DateTimeDataField dt)");
            builder.AppendLine("        {");
            builder.AppendLine("            unit = dt.DateTimeFormat switch");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                global::Parquet.Schema.DateTimeFormat.DateAndTime => global::Apache.Arrow.Types.TimeUnit.Millisecond,"
            );
            builder.AppendLine(
                "                _ => global::Apache.Arrow.Types.TimeUnit.Microsecond,"
            );
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine(
                "        return new global::Apache.Arrow.Types.TimestampType(unit, (string?)null);"
            );
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Converts a decoded <c>DateTime</c> to the Arrow storage integer for the column's unit."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static long ToArrowTimestamp(global::System.DateTime value, global::Apache.Arrow.Types.TimeUnit unit)"
            );
            builder.AppendLine("    {");
            builder.AppendLine("        long ticks = value.Ticks - 621355968000000000L;");
            builder.AppendLine("        return unit switch");
            builder.AppendLine("        {");
            builder.AppendLine(
                "            global::Apache.Arrow.Types.TimeUnit.Second => ticks / 10000000L,"
            );
            builder.AppendLine(
                "            global::Apache.Arrow.Types.TimeUnit.Millisecond => ticks / 10000L,"
            );
            builder.AppendLine(
                "            global::Apache.Arrow.Types.TimeUnit.Nanosecond => ticks * 100L,"
            );
            builder.AppendLine("            _ => ticks / 10L,");
            builder.AppendLine("        };");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        if (hasTime)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// <c>TimeOnly</c> columns are written as TIME(MICROS), so Arrow gets Time64 microseconds."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static global::Apache.Arrow.Types.Time64Type ArrowTimeType()"
            );
            builder.AppendLine(
                "        => new global::Apache.Arrow.Types.Time64Type(global::Apache.Arrow.Types.TimeUnit.Microsecond);"
            );
            builder.AppendLine();
        }

        if (hasDate)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Date32 counts whole days from the Unix epoch; the decoded value is midnight-anchored."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static int ToArrowDate32(global::System.DateTime value)"
            );
            builder.AppendLine(
                "        => (int)((value.Date.Ticks - 621355968000000000L) / 864000000000L);"
            );
            builder.AppendLine();
        }

        if (hasGuid)
        {
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Arrow's C# library has no UUID logical type, so GUIDs export as fixed_size_binary(16)."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static global::Apache.Arrow.Types.FixedSizeBinaryType ArrowUuidType()"
            );
            builder.AppendLine(
                "        => new global::Apache.Arrow.Types.FixedSizeBinaryType(16);"
            );
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                "    /// Writes a GUID in RFC 4122 byte order (big-endian first three groups), which is what every"
            );
            builder.AppendLine(
                "    /// non-.NET UUID reader expects — <c>Guid.TryWriteBytes</c> alone emits the .NET layout."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                "    private static void WriteArrowUuid(global::System.Guid value, global::System.Span<byte> destination)"
            );
            builder.AppendLine("    {");
            builder.AppendLine("        value.TryWriteBytes(destination);");
            builder.AppendLine("        byte t;");
            builder.AppendLine(
                "        t = destination[0]; destination[0] = destination[3]; destination[3] = t;"
            );
            builder.AppendLine(
                "        t = destination[1]; destination[1] = destination[2]; destination[2] = t;"
            );
            builder.AppendLine(
                "        t = destination[4]; destination[4] = destination[5]; destination[5] = t;"
            );
            builder.AppendLine(
                "        t = destination[6]; destination[6] = destination[7]; destination[7] = t;"
            );
            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    // ──────────────────────────────────────────────────────────
    //  READ SURFACE
    // ──────────────────────────────────────────────────────────

    private static void EmitReadRecordBatchesAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Streams <c>{model.ClassName}</c> columns out of a Parquet stream as Apache Arrow"
        );
        builder.AppendLine(
            "    /// <c>RecordBatch</c>es — one per row group, split further when <paramref name=\"maxRowsPerBatch\"/>"
        );
        builder.AppendLine(
            "    /// is set. No POCO is constructed: column buffers are decoded once and copied straight into"
        );
        builder.AppendLine("    /// Arrow-owned buffers.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            "    /// <remarks>Each batch owns its buffers; dispose a batch when done with it.</remarks>"
        );
        builder.AppendLine(
            "    public static async global::System.Collections.Generic.IAsyncEnumerable<global::Apache.Arrow.RecordBatch> ReadParquetRecordBatchesAsync("
        );
        builder.AppendLine("        this global::System.IO.Stream stream,");
        builder.AppendLine(
            "        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine("        int? maxRowsPerBatch = null,");
        builder.AppendLine(
            "        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine("        if (maxRowsPerBatch.HasValue && maxRowsPerBatch.Value <= 0)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            throw new global::System.ArgumentOutOfRangeException(nameof(maxRowsPerBatch), maxRowsPerBatch.Value, \"maxRowsPerBatch must be positive.\");"
        );
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();
        builder.AppendLine(
            "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
        );
        for (int i = 0; i < model.Properties.Length; i++)
        {
            builder.AppendLine(
                $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
            );
        }
        builder.AppendLine();
        builder.Append("        var batchSchema = BuildArrowSchema(");
        for (int i = 0; i < model.Properties.Length; i++)
        {
            builder.Append(i == 0 ? "" : ", ");
            builder.Append($"field_{i}");
        }
        builder.AppendLine(");");
        builder.AppendLine();
        builder.AppendLine("        for (int r = 0; r < reader.RowGroupCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("            int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine("            if (rowCount == 0) continue;");
        builder.AppendLine();
        BufferPoolComponent.EmitRentals(builder, model, "rowCount", indent: "            ");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        foreach ((int i, PropertyModel prop, ArrowMapping _) in Columns(model))
        {
            CodeEmitter.EmitReadPrimitiveColumn(builder, prop, i, $"field_{i}", $"buffer_{i}");
        }
        builder.AppendLine();
        builder.AppendLine("                int produced = 0;");
        builder.AppendLine("                while (produced < rowCount)");
        builder.AppendLine("                {");
        builder.AppendLine("                    int take = maxRowsPerBatch.HasValue");
        builder.AppendLine(
            "                        ? global::System.Math.Min(maxRowsPerBatch.Value, rowCount - produced)"
        );
        builder.AppendLine("                        : rowCount - produced;");
        builder.AppendLine(
            $"                    var columns = new global::Apache.Arrow.IArrowArray[{model.Properties.Length}];"
        );
        for (int i = 0; i < model.Properties.Length; i++)
        {
            builder.AppendLine(
                $"                    columns[{i}] = BuildArrowColumn_{i}(buffer_{i}, produced, take, field_{i});"
            );
        }
        builder.AppendLine(
            "                    yield return new global::Apache.Arrow.RecordBatch(batchSchema, columns, take);"
        );
        builder.AppendLine("                    produced += take;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    // ──────────────────────────────────────────────────────────
    //  PER-COLUMN ARROW ARRAY BUILDERS
    // ──────────────────────────────────────────────────────────

    private static void EmitColumnBuilders(StringBuilder builder, TargetClassModel model)
    {
        foreach ((int i, PropertyModel prop, ArrowMapping map) in Columns(model))
        {
            string bufferType = BufferPoolComponent.GetBufferElementType(prop);
            builder.AppendLine("    /// <summary>");
            builder.AppendLine(
                $"    /// Copies <c>{prop.ParquetColumnName}</c> out of its rented column buffer into an Arrow array."
            );
            builder.AppendLine("    /// </summary>");
            builder.AppendLine(
                $"    private static global::Apache.Arrow.IArrowArray BuildArrowColumn_{i}("
            );
            builder.AppendLine($"        {bufferType}[] source,");
            builder.AppendLine("        int offset,");
            builder.AppendLine("        int count,");
            builder.AppendLine("        global::Parquet.Schema.DataField field)");
            builder.AppendLine("    {");
            EmitColumnBody(builder, prop, map);
            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    private static void EmitColumnBody(StringBuilder builder, PropertyModel prop, ArrowMapping map)
    {
        const string ind = "        ";
        bool nullable = prop.IsNullable;

        switch (map)
        {
            case ArrowMapping.Boolean:
                EmitBooleanBody(builder, ind, nullable);
                return;
            case ArrowMapping.Utf8:
                EmitUtf8Body(builder, ind, nullable);
                return;
            case ArrowMapping.Binary:
                EmitBinaryBody(builder, ind, nullable);
                return;
            case ArrowMapping.Decimal128:
                EmitDecimalBody(builder, ind, nullable);
                return;
            case ArrowMapping.FixedSizeBinary16:
                EmitGuidBody(builder, ind, nullable);
                return;
            default:
                EmitFixedWidthBody(builder, ind, prop, map, nullable);
                return;
        }
    }

    /// <summary>
    /// The conversion from a decoded buffer value to the Arrow storage integer, or null when the
    /// buffer already holds exactly the storage representation.
    /// </summary>
    private static string? StorageConversion(ArrowMapping map) =>
        map switch
        {
            ArrowMapping.Timestamp => "ToArrowTimestamp({0}, arrowType.Unit)",
            ArrowMapping.Date32 => "ToArrowDate32({0})",
            ArrowMapping.Duration => "(long){0}",
            ArrowMapping.MonthDayNanosecondInterval =>
                "new global::Apache.Arrow.Scalars.MonthDayNanosecondInterval(({0}).Months, ({0}).Days, ({0}).Millis * 1000000L)",
            _ => null,
        };

    private static void EmitFixedWidthBody(
        StringBuilder builder,
        string ind,
        PropertyModel prop,
        ArrowMapping map,
        bool nullable
    )
    {
        string storage = ArrowMappingComponent.FixedWidthStorageType(map)!;
        string arrayType = ArrowMappingComponent.ArrayTypeName(map);
        string? conversion = StorageConversion(map);
        bool typedCtor =
            map is ArrowMapping.Timestamp or ArrowMapping.Time64 or ArrowMapping.Duration;

        if (map == ArrowMapping.Timestamp)
        {
            builder.AppendLine($"{ind}var arrowType = ArrowTimestampType(field);");
        }
        else if (map == ArrowMapping.Time64)
        {
            builder.AppendLine($"{ind}var arrowType = ArrowTimeType();");
        }
        else if (map == ArrowMapping.Duration)
        {
            builder.AppendLine(
                $"{ind}var arrowType = global::Apache.Arrow.Types.DurationType.Millisecond;"
            );
        }

        builder.AppendLine(
            $"{ind}var values = new global::Apache.Arrow.ArrowBuffer.Builder<{storage}>(count > 0 ? count : 1);"
        );

        if (!nullable && conversion is null)
        {
            builder.AppendLine(
                $"{ind}values.Append(new global::System.ReadOnlySpan<{storage}>(source, offset, count));"
            );
            builder.AppendLine(
                $"{ind}return {Construct(arrayType, typedCtor, "values.Build()", "global::Apache.Arrow.ArrowBuffer.Empty", "count", "0")};"
            );
            return;
        }

        if (!nullable)
        {
            builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
            builder.AppendLine($"{ind}{{");
            builder.AppendLine(
                $"{ind}    values.Append({string.Format(System.Globalization.CultureInfo.InvariantCulture, conversion!, "source[offset + i]")});"
            );
            builder.AppendLine($"{ind}}}");
            builder.AppendLine();
            builder.AppendLine(
                $"{ind}return {Construct(arrayType, typedCtor, "values.Build()", "global::Apache.Arrow.ArrowBuffer.Empty", "count", "0")};"
            );
            return;
        }

        builder.AppendLine(
            $"{ind}var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        builder.AppendLine($"{ind}int nullCount = 0;");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        builder.AppendLine($"{ind}    if (slot.HasValue)");
        builder.AppendLine($"{ind}    {{");
        string valueExpr = "slot.GetValueOrDefault()";
        string appended = conversion is null
            ? valueExpr
            : string.Format(
                System.Globalization.CultureInfo.InvariantCulture,
                conversion,
                valueExpr
            );
        builder.AppendLine($"{ind}        values.Append({appended});");
        builder.AppendLine($"{ind}        validity.Append(true);");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine($"{ind}    else");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine($"{ind}        values.Append(default({storage}));");
        builder.AppendLine($"{ind}        validity.Append(false);");
        builder.AppendLine($"{ind}        nullCount++;");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine(
            $"{ind}return {Construct(arrayType, typedCtor, "values.Build()", "validity.Build()", "count", "nullCount")};"
        );
    }

    private static string Construct(
        string arrayType,
        bool typedCtor,
        string values,
        string validity,
        string count,
        string nullCount
    ) =>
        typedCtor
            ? $"new {arrayType}(arrowType, {values}, {validity}, {count}, {nullCount}, 0)"
            : $"new {arrayType}({values}, {validity}, {count}, {nullCount}, 0)";

    private static void EmitBooleanBody(StringBuilder builder, string ind, bool nullable)
    {
        builder.AppendLine(
            $"{ind}var values = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        if (!nullable)
        {
            builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
            builder.AppendLine($"{ind}{{");
            builder.AppendLine($"{ind}    values.Append(source[offset + i]);");
            builder.AppendLine($"{ind}}}");
            builder.AppendLine();
            builder.AppendLine(
                $"{ind}return new global::Apache.Arrow.BooleanArray(values.Build(), global::Apache.Arrow.ArrowBuffer.Empty, count, 0, 0);"
            );
            return;
        }

        builder.AppendLine(
            $"{ind}var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        builder.AppendLine($"{ind}int nullCount = 0;");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        builder.AppendLine($"{ind}    values.Append(slot.GetValueOrDefault());");
        builder.AppendLine($"{ind}    validity.Append(slot.HasValue);");
        builder.AppendLine($"{ind}    if (!slot.HasValue) nullCount++;");
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine(
            $"{ind}return new global::Apache.Arrow.BooleanArray(values.Build(), validity.Build(), count, nullCount, 0);"
        );
    }

    private static void EmitUtf8Body(StringBuilder builder, string ind, bool nullable)
    {
        builder.AppendLine(
            $"{ind}var offsets = new global::Apache.Arrow.ArrowBuffer.Builder<int>(count + 1);"
        );
        builder.AppendLine(
            $"{ind}var data = new global::Apache.Arrow.ArrowBuffer.Builder<byte>(count > 0 ? count * 8 : 1);"
        );
        builder.AppendLine(
            $"{ind}var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        builder.AppendLine($"{ind}int nullCount = 0;");
        builder.AppendLine($"{ind}int cursor = 0;");
        builder.AppendLine($"{ind}offsets.Append(0);");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        builder.AppendLine($"{ind}    if (slot is null)");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine($"{ind}        validity.Append(false);");
        builder.AppendLine($"{ind}        nullCount++;");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine($"{ind}    else");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine($"{ind}        if (slot.Length > 0)");
        builder.AppendLine($"{ind}        {{");
        builder.AppendLine(
            $"{ind}            var encoded = global::System.Text.Encoding.UTF8.GetBytes(slot);"
        );
        builder.AppendLine(
            $"{ind}            data.Append(new global::System.ReadOnlySpan<byte>(encoded));"
        );
        builder.AppendLine($"{ind}            cursor += encoded.Length;");
        builder.AppendLine($"{ind}        }}");
        builder.AppendLine($"{ind}        validity.Append(true);");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine();
        builder.AppendLine($"{ind}    offsets.Append(cursor);");
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine($"{ind}return new global::Apache.Arrow.StringArray(");
        builder.AppendLine($"{ind}    count,");
        builder.AppendLine($"{ind}    offsets.Build(),");
        builder.AppendLine($"{ind}    data.Build(),");
        builder.AppendLine(
            nullable
                ? $"{ind}    validity.Build(),"
                : $"{ind}    nullCount == 0 ? global::Apache.Arrow.ArrowBuffer.Empty : validity.Build(),"
        );
        builder.AppendLine($"{ind}    nullCount,");
        builder.AppendLine($"{ind}    0);");
    }

    private static void EmitBinaryBody(StringBuilder builder, string ind, bool nullable)
    {
        builder.AppendLine(
            $"{ind}var offsets = new global::Apache.Arrow.ArrowBuffer.Builder<int>(count + 1);"
        );
        builder.AppendLine(
            $"{ind}var data = new global::Apache.Arrow.ArrowBuffer.Builder<byte>(count > 0 ? count * 8 : 1);"
        );
        builder.AppendLine(
            $"{ind}var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        builder.AppendLine($"{ind}int nullCount = 0;");
        builder.AppendLine($"{ind}int cursor = 0;");
        builder.AppendLine($"{ind}offsets.Append(0);");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        builder.AppendLine($"{ind}    if (slot is null)");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine($"{ind}        validity.Append(false);");
        builder.AppendLine($"{ind}        nullCount++;");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine($"{ind}    else");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine($"{ind}        if (slot.Length > 0)");
        builder.AppendLine($"{ind}        {{");
        builder.AppendLine(
            $"{ind}            data.Append(new global::System.ReadOnlySpan<byte>(slot));"
        );
        builder.AppendLine($"{ind}            cursor += slot.Length;");
        builder.AppendLine($"{ind}        }}");
        builder.AppendLine($"{ind}        validity.Append(true);");
        builder.AppendLine($"{ind}    }}");
        builder.AppendLine();
        builder.AppendLine($"{ind}    offsets.Append(cursor);");
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine($"{ind}return new global::Apache.Arrow.BinaryArray(");
        builder.AppendLine($"{ind}    global::Apache.Arrow.Types.BinaryType.Default,");
        builder.AppendLine($"{ind}    count,");
        builder.AppendLine($"{ind}    offsets.Build(),");
        builder.AppendLine($"{ind}    data.Build(),");
        builder.AppendLine(
            nullable
                ? $"{ind}    validity.Build(),"
                : $"{ind}    nullCount == 0 ? global::Apache.Arrow.ArrowBuffer.Empty : validity.Build(),"
        );
        builder.AppendLine($"{ind}    nullCount,");
        builder.AppendLine($"{ind}    0);");
    }

    private static void EmitDecimalBody(StringBuilder builder, string ind, bool nullable)
    {
        builder.AppendLine($"{ind}var arrowType = ArrowDecimalType(field);");
        builder.AppendLine(
            $"{ind}var arrayBuilder = new global::Apache.Arrow.Decimal128Array.Builder(arrowType);"
        );
        builder.AppendLine($"{ind}arrayBuilder.Reserve(count > 0 ? count : 1);");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        if (nullable)
        {
            builder.AppendLine($"{ind}    if (slot.HasValue)");
            builder.AppendLine($"{ind}    {{");
            builder.AppendLine($"{ind}        arrayBuilder.Append(slot.GetValueOrDefault());");
            builder.AppendLine($"{ind}    }}");
            builder.AppendLine($"{ind}    else");
            builder.AppendLine($"{ind}    {{");
            builder.AppendLine($"{ind}        arrayBuilder.AppendNull();");
            builder.AppendLine($"{ind}    }}");
        }
        else
        {
            builder.AppendLine($"{ind}    arrayBuilder.Append(slot);");
        }
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine($"{ind}return arrayBuilder.Build();");
    }

    private static void EmitGuidBody(StringBuilder builder, string ind, bool nullable)
    {
        builder.AppendLine($"{ind}var arrowType = ArrowUuidType();");
        builder.AppendLine(
            $"{ind}var values = new global::Apache.Arrow.ArrowBuffer.Builder<byte>(count > 0 ? count * 16 : 1);"
        );
        builder.AppendLine(
            $"{ind}var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count > 0 ? count : 1);"
        );
        builder.AppendLine($"{ind}int nullCount = 0;");
        builder.AppendLine($"{ind}global::System.Span<byte> scratch = stackalloc byte[16];");
        builder.AppendLine($"{ind}for (int i = 0; i < count; i++)");
        builder.AppendLine($"{ind}{{");
        builder.AppendLine($"{ind}    var slot = source[offset + i];");
        if (nullable)
        {
            builder.AppendLine($"{ind}    if (slot.HasValue)");
            builder.AppendLine($"{ind}    {{");
            builder.AppendLine($"{ind}        WriteArrowUuid(slot.GetValueOrDefault(), scratch);");
            builder.AppendLine($"{ind}        validity.Append(true);");
            builder.AppendLine($"{ind}    }}");
            builder.AppendLine($"{ind}    else");
            builder.AppendLine($"{ind}    {{");
            builder.AppendLine($"{ind}        scratch.Clear();");
            builder.AppendLine($"{ind}        validity.Append(false);");
            builder.AppendLine($"{ind}        nullCount++;");
            builder.AppendLine($"{ind}    }}");
        }
        else
        {
            builder.AppendLine($"{ind}    WriteArrowUuid(slot, scratch);");
            builder.AppendLine($"{ind}    validity.Append(true);");
        }
        builder.AppendLine();
        builder.AppendLine($"{ind}    values.Append(scratch);");
        builder.AppendLine($"{ind}}}");
        builder.AppendLine();
        builder.AppendLine(
            $"{ind}return new global::Apache.Arrow.Arrays.FixedSizeBinaryArray(new global::Apache.Arrow.ArrayData("
        );
        builder.AppendLine($"{ind}    arrowType,");
        builder.AppendLine($"{ind}    count,");
        builder.AppendLine($"{ind}    nullCount,");
        builder.AppendLine($"{ind}    0,");
        builder.AppendLine($"{ind}    new global::Apache.Arrow.ArrowBuffer[]");
        builder.AppendLine($"{ind}    {{");
        builder.AppendLine(
            nullable
                ? $"{ind}        validity.Build(),"
                : $"{ind}        global::Apache.Arrow.ArrowBuffer.Empty,"
        );
        builder.AppendLine($"{ind}        values.Build(),");
        builder.AppendLine($"{ind}    }},");
        builder.AppendLine(
            $"{ind}    global::System.Array.Empty<global::Apache.Arrow.ArrayData>()));"
        );
    }
}
