using System;
using System.Text;
using Parquet.SourceGenerator.Models;

namespace Parquet.SourceGenerator.Legacy.Emitter;

/// <summary>
/// Emits C# partial extension classes targeting Parquet.Net v4 / v5 (DataColumn-based API).
/// Provides compatibility for .NET Framework 4.7.2, .NET Standard 2.0, and Parquet.Net 4.x/5.x releases.
/// </summary>
public static partial class LegacyCodeEmitter
{
    /// <summary>
    /// Generates complete C# source code string for a target model using Parquet.Net v4/v5 APIs.
    /// </summary>
    public static string EmitSource(TargetClassModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629");
        builder.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }

        string extensionsClassName = $"{model.ClassName}ParquetLegacyExtensions";

        builder.AppendLine($"public static partial class {extensionsClassName}");
        builder.AppendLine("{");

        EmitSchema(builder, model);
        builder.AppendLine();

        EmitStaticFields(builder, model);
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            EmitResolveSchemaField(builder);
            builder.AppendLine();
        }

        EmitBuildFormatOptions(builder);
        builder.AppendLine();

        EmitApplyCompression(builder);
        builder.AppendLine();

        EmitWriteRowGroupAsync(builder, model);
        builder.AppendLine();

        EmitWriteAsync(builder, model);
        builder.AppendLine();

        EmitWriteBatchedAsync(builder, model);
        builder.AppendLine();

        EmitReadAsync(builder, model);
        builder.AppendLine();

        builder.AppendLine("}");

        return builder.ToString();
    }
}
