// <auto-generated />
#nullable enable
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629

namespace SampleDomain.Models;

public static partial class LegacyRecordParquetLegacyExtensions
{
    /// <summary>
    /// Static compile-time <c>Parquet.Schema.ParquetSchema</c> for <c>LegacyRecord</c>.
    /// </summary>
    public static readonly global::Parquet.Schema.ParquetSchema Schema = new global::Parquet.Schema.ParquetSchema(
        new global::Parquet.Schema.DataField("id", typeof(int), isNullable: false),
        new global::Parquet.Schema.DataField("desc", typeof(string), isNullable: true),
        new global::Parquet.Schema.DataField("raw_data", typeof(byte[]), isNullable: true),
        new global::Parquet.Schema.DataField("level", typeof(int), isNullable: false)
    );

    private static readonly global::Parquet.Schema.DataField _field_0 = (global::Parquet.Schema.DataField)Schema.Fields[0];
    private static readonly global::Parquet.Schema.DataField _field_1 = (global::Parquet.Schema.DataField)Schema.Fields[1];
    private static readonly global::Parquet.Schema.DataField _field_2 = (global::Parquet.Schema.DataField)Schema.Fields[2];
    private static readonly global::Parquet.Schema.DataField _field_3 = (global::Parquet.Schema.DataField)Schema.Fields[3];

    /// <summary>
    /// Resolves one generated schema field against the fields actually present in the file.
    /// </summary>
    private static global::Parquet.Schema.DataField ResolveSchemaField(
        global::Parquet.Schema.DataField[] fileFields,
        int index,
        global::Parquet.Schema.DataField expected,
        ref global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? byName)
    {
        string expectedPath = expected.Path.ToString();

        // Ordered schemas resolve on a single index check. Every file this generator writes lands
        // here, as does any file whose column order matches; the linear scan below is only for
        // files written with a different column order.
        if ((uint)index < (uint)fileFields.Length
            && string.Equals(fileFields[index].Path.ToString(), expectedPath, global::System.StringComparison.OrdinalIgnoreCase))
        {
            return fileFields[index];
        }

        if (byName is null)
        {
            byName = new global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>(
                fileFields.Length, global::System.StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < fileFields.Length; i++)
            {
                // First occurrence wins if a file carries duplicate column names. Dictionary.TryAdd is
                // not available to netstandard2.0 consumers, hence the explicit containment check.
                string path = fileFields[i].Path.ToString();
                if (!byName.ContainsKey(path))
                {
                    byName.Add(path, fileFields[i]);
                }
            }
        }

        return byName.TryGetValue(expectedPath, out var matched) ? matched : expected;
    }

    /// <summary>
    /// Translates the generator's options into the Parquet.Net options the reader and writer accept.
    /// </summary>
    /// <remarks>
    /// Parquet.Net v4/v5 keeps compression on <c>ParquetWriter</c> rather than on
    /// <c>ParquetOptions</c> — see <c>ApplyCompression</c>. <c>ParquetOptions</c> itself carries only
    /// decoding hints (<c>TreatByteArrayAsString</c> and friends) that this generator does not
    /// currently expose, so the returned instance is deliberately left at its defaults.
    /// </remarks>
    private static global::Parquet.ParquetOptions BuildFormatOptions(
        global::Parquet.SourceGenerator.ParquetSerializerOptions options)
    {
        return new global::Parquet.ParquetOptions();
    }

    /// <summary>
    /// Applies the requested compression settings to a v4/v5 writer.
    /// </summary>
    /// <remarks>
    /// <c>CompressionMethod</c> is a property and <c>CompressionLevel</c> a field on
    /// <c>ParquetWriter</c> in this API generation; both must be set after the writer exists and
    /// before the first row group is written. Without this, every option was silently discarded and
    /// a Gzip request wrote Snappy.
    /// </remarks>
    private static void ApplyCompression(
        global::Parquet.ParquetWriter writer,
        global::Parquet.SourceGenerator.ParquetSerializerOptions options)
    {
        writer.CompressionMethod = options.CompressionMethod switch
        {
            global::Parquet.SourceGenerator.ParquetCompressionMethod.None =>
                global::Parquet.CompressionMethod.None,
            global::Parquet.SourceGenerator.ParquetCompressionMethod.Gzip =>
                global::Parquet.CompressionMethod.Gzip,
            // Parquet.Net spells this one in caps.
            global::Parquet.SourceGenerator.ParquetCompressionMethod.Lz4 =>
                global::Parquet.CompressionMethod.LZ4,
            global::Parquet.SourceGenerator.ParquetCompressionMethod.Brotli =>
                global::Parquet.CompressionMethod.Brotli,
            global::Parquet.SourceGenerator.ParquetCompressionMethod.Zstd =>
                global::Parquet.CompressionMethod.Zstd,
            _ => global::Parquet.CompressionMethod.Snappy,
        };

        if (!options.CompressionLevel.HasValue) return;

        switch (options.CompressionLevel.Value)
        {
            case global::Parquet.SourceGenerator.ParquetCompressionLevel.Fastest:
                writer.CompressionLevel = global::System.IO.Compression.CompressionLevel.Fastest;
                break;
            case global::Parquet.SourceGenerator.ParquetCompressionLevel.NoCompression:
                writer.CompressionLevel = global::System.IO.Compression.CompressionLevel.NoCompression;
                break;
#if NET6_0_OR_GREATER
            case global::Parquet.SourceGenerator.ParquetCompressionLevel.SmallestSize:
                writer.CompressionLevel = global::System.IO.Compression.CompressionLevel.SmallestSize;
                break;
#endif
            default:
                // Includes SmallestSize below .NET 6, where Optimal is the strongest level available.
                writer.CompressionLevel = global::System.IO.Compression.CompressionLevel.Optimal;
                break;
        }
    }

    /// <summary>
    /// Writes a single row group chunk using Parquet.Net DataColumn primitives.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteRowGroupAsync(
        this global::Parquet.ParquetWriter writer,
        global::System.Collections.Generic.IReadOnlyList<LegacyRecord> items,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (writer == null) throw new global::System.ArgumentNullException(nameof(writer));
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));

        int count = items.Count;
        if (count == 0) return;

        var colArray_0 = new int[count];
        var colArray_1 = new string[count];
        var colArray_2 = new byte[count][];
        var colArray_3 = new int[count];

        for (int k = 0; k < count; k++)
        {
            var item = items[k];
            colArray_0[k] = item.Id;
            colArray_1[k] = item.Description;
            colArray_2[k] = item.RawData;
            colArray_3[k] = (int)item.Level;
        }

        using (var rgWriter = writer.CreateRowGroup())
        {
            var col_0 = new global::Parquet.Data.DataColumn(_field_0, colArray_0);
            await rgWriter.WriteColumnAsync(col_0, cancellationToken).ConfigureAwait(false);
            var col_1 = new global::Parquet.Data.DataColumn(_field_1, colArray_1);
            await rgWriter.WriteColumnAsync(col_1, cancellationToken).ConfigureAwait(false);
            var col_2 = new global::Parquet.Data.DataColumn(_field_2, colArray_2);
            await rgWriter.WriteColumnAsync(col_2, cancellationToken).ConfigureAwait(false);
            var col_3 = new global::Parquet.Data.DataColumn(_field_3, colArray_3);
            await rgWriter.WriteColumnAsync(col_3, cancellationToken).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Asynchronously serializes all <c>LegacyRecord</c> items to stream using Parquet.Net v4/v5.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetAsync(
        this global::System.Collections.Generic.IReadOnlyList<LegacyRecord> items,
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        using (var writer = await global::Parquet.ParquetWriter.CreateAsync(Schema, stream, BuildFormatOptions(options), cancellationToken: cancellationToken).ConfigureAwait(false))
        {
            ApplyCompression(writer, options);
            await writer.WriteRowGroupAsync(items, cancellationToken).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Asynchronously serializes items in fixed-size row group chunks.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetBatchedAsync(
        this global::System.Collections.Generic.IEnumerable<LegacyRecord> items,
        global::System.IO.Stream stream,
        int? rowGroupSize = null,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        if (rowGroupSize.HasValue && rowGroupSize.Value <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(rowGroupSize));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        int batchSize = rowGroupSize ?? options.RowGroupSize;
        if (batchSize <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(options), "ParquetSerializerOptions.RowGroupSize must be greater than zero.");

        using (var writer = await global::Parquet.ParquetWriter.CreateAsync(Schema, stream, BuildFormatOptions(options), cancellationToken: cancellationToken).ConfigureAwait(false))
        {
            ApplyCompression(writer, options);
            var chunk = new global::System.Collections.Generic.List<LegacyRecord>(batchSize);
            foreach (var item in items)
            {
                cancellationToken.ThrowIfCancellationRequested();
                chunk.Add(item);
                if (chunk.Count >= batchSize)
                {
                    await writer.WriteRowGroupAsync(chunk, cancellationToken).ConfigureAwait(false);
                    chunk.Clear();
                }
            }
            if (chunk.Count > 0)
            {
                await writer.WriteRowGroupAsync(chunk, cancellationToken).ConfigureAwait(false);
            }
        }
    }

    /// <summary>
    /// Asynchronously deserializes all <c>LegacyRecord</c> objects from a Parquet stream using Parquet.Net v4/v5.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<LegacyRecord>> ReadParquetAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        using (var reader = await global::Parquet.ParquetReader.CreateAsync(stream, BuildFormatOptions(options), cancellationToken: cancellationToken).ConfigureAwait(false))
        {
            int rgCount = reader.RowGroupCount;
            if (rgCount == 0) return new global::System.Collections.Generic.List<LegacyRecord>();

            int totalRows = 0;
            var rowOffsets = new int[rgCount];
            for (int r = 0; r < rgCount; r++)
            {
                rowOffsets[r] = totalRows;
                totalRows += (int)reader.RowGroups[r].RowCount;
            }

            var resultArray = new LegacyRecord[totalRows];
            var fileFields = reader.Schema.GetDataFields();
            global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
            var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
            var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
            var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
            var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);

            for (int r = 0; r < rgCount; r++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                using (var rgReader = reader.OpenRowGroupReader(r))
                {
                    int groupRows = (int)rgReader.RowCount;
                    if (groupRows == 0) continue;
                    int startIdx = rowOffsets[r];

                    var col_0 = await rgReader.ReadColumnAsync(field_0, cancellationToken).ConfigureAwait(false);
                    var data_0 = (int[])col_0.Data;
                    var col_1 = await rgReader.ReadColumnAsync(field_1, cancellationToken).ConfigureAwait(false);
                    var data_1 = (string[])col_1.Data;
                    var col_2 = await rgReader.ReadColumnAsync(field_2, cancellationToken).ConfigureAwait(false);
                    var data_2 = (byte[][])col_2.Data;
                    var col_3 = await rgReader.ReadColumnAsync(field_3, cancellationToken).ConfigureAwait(false);
                    var data_3 = (int[])col_3.Data;

                    for (int k = 0; k < groupRows; k++)
                    {
                        resultArray[startIdx + k] = new LegacyRecord
                        {
                            Id = data_0[k],
                            Description = data_1[k],
                            RawData = data_2[k],
                            Level = (SampleDomain.Models.AccessLevel)data_3[k],
                        };
                    }
                }
            }
            return new global::System.Collections.Generic.List<LegacyRecord>(resultArray);
        }
    }

}
