// <auto-generated />
#nullable enable
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629

namespace SampleDomain.Models;

public static partial class ScalarMetricParquetExtensions
{
    /// <summary>
    /// Static compile-time <c>Parquet.Schema.ParquetSchema</c> for <c>ScalarMetric</c>.
    /// </summary>
    public static readonly global::Parquet.Schema.ParquetSchema Schema = new global::Parquet.Schema.ParquetSchema(
        new global::Parquet.Schema.DataField("row_id", typeof(long), isNullable: false),
        new global::Parquet.Schema.DataField("is_valid", typeof(bool), isNullable: false),
        new global::Parquet.Schema.DataField("maybe_flag", typeof(bool), isNullable: true),
        new global::Parquet.Schema.DataField("status", typeof(int), isNullable: false),
        new global::Parquet.Schema.DataField("opt_status", typeof(int), isNullable: true),
        new global::Parquet.Schema.DataField("tiny_num", typeof(byte), isNullable: false),
        new global::Parquet.Schema.DataField("short_num", typeof(short), isNullable: false),
        new global::Parquet.Schema.DataField("float_val", typeof(float), isNullable: false)
    );

    private static readonly global::Parquet.Schema.DataField _field_0 = (global::Parquet.Schema.DataField)Schema.Fields[0];
    private static readonly global::Parquet.Schema.DataField _field_1 = (global::Parquet.Schema.DataField)Schema.Fields[1];
    private static readonly global::Parquet.Schema.DataField _field_2 = (global::Parquet.Schema.DataField)Schema.Fields[2];
    private static readonly global::Parquet.Schema.DataField _field_3 = (global::Parquet.Schema.DataField)Schema.Fields[3];
    private static readonly global::Parquet.Schema.DataField _field_4 = (global::Parquet.Schema.DataField)Schema.Fields[4];
    private static readonly global::Parquet.Schema.DataField _field_5 = (global::Parquet.Schema.DataField)Schema.Fields[5];
    private static readonly global::Parquet.Schema.DataField _field_6 = (global::Parquet.Schema.DataField)Schema.Fields[6];
    private static readonly global::Parquet.Schema.DataField _field_7 = (global::Parquet.Schema.DataField)Schema.Fields[7];

    /// <summary>
    /// Resolves one generated schema field against the fields actually present in the file.
    /// </summary>
    private static global::Parquet.Schema.DataField ResolveSchemaField(
        global::Parquet.Schema.DataField[] fileFields,
        int index,
        global::Parquet.Schema.DataField expected,
        ref global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? byName)
    {
        // Ordered schemas resolve on a single index check: no hashing, no delegate, no allocation.
        // Every file this generator writes lands here, as does any file whose column order matches.
        if ((uint)index < (uint)fileFields.Length
            && string.Equals(fileFields[index].Name, expected.Name, global::System.StringComparison.OrdinalIgnoreCase))
        {
            return fileFields[index];
        }

        // Only a file whose column order differs reaches here. The name index is built at most once
        // per read and reused for every subsequent miss, so even a fully reordered schema costs O(n)
        // in total rather than a linear scan per field.
        if (byName is null)
        {
            byName = new global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>(
                fileFields.Length, global::System.StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < fileFields.Length; i++)
            {
                // First occurrence wins if a file carries duplicate column names. Dictionary.TryAdd is
                // not available to netstandard2.0 consumers, hence the explicit containment check.
                if (!byName.ContainsKey(fileFields[i].Name))
                {
                    byName.Add(fileFields[i].Name, fileFields[i]);
                }
            }
        }

        return byName.TryGetValue(expected.Name, out var match) ? match : expected;
    }

    /// <summary>
    /// Translates the generator's options into the Parquet.Net options the writer accepts.
    /// </summary>
    private static global::Parquet.ParquetOptions BuildFormatOptions(
        global::Parquet.SourceGenerator.ParquetSerializerOptions options)
    {
        var formatOptions = new global::Parquet.ParquetOptions
        {
            CompressionMethod = options.CompressionMethod switch
            {
                global::Parquet.SourceGenerator.ParquetCompressionMethod.None =>
                    global::Parquet.CompressionMethod.None,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Gzip =>
                    global::Parquet.CompressionMethod.Gzip,
                // Parquet.Net spells this one in caps.
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Lz4 =>
                    global::Parquet.CompressionMethod.LZ4,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Brotli =>
                    global::Parquet.CompressionMethod.Brotli,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Zstd =>
                    global::Parquet.CompressionMethod.Zstd,
                _ => global::Parquet.CompressionMethod.Snappy,
            },
        };

        if (options.CompressionLevel.HasValue)
        {
            formatOptions.CompressionLevel = options.CompressionLevel.Value switch
            {
                global::Parquet.SourceGenerator.ParquetCompressionLevel.Optimal =>
                    global::System.IO.Compression.CompressionLevel.Optimal,
                global::Parquet.SourceGenerator.ParquetCompressionLevel.Fastest =>
                    global::System.IO.Compression.CompressionLevel.Fastest,
                global::Parquet.SourceGenerator.ParquetCompressionLevel.NoCompression =>
                    global::System.IO.Compression.CompressionLevel.NoCompression,
                _ => global::System.IO.Compression.CompressionLevel.SmallestSize,
            };
        }

        return formatOptions;
    }

    /// <summary>
    /// Writes a single row group chunk using Parquet.Net low-level primitives for maximum speed and Native AOT compatibility.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetRowGroupAsync(
        this global::Parquet.ParquetWriter writer,
        global::System.Collections.Generic.IReadOnlyCollection<ScalarMetric> chunk,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (writer == null) throw new global::System.ArgumentNullException(nameof(writer));
        if (chunk == null) throw new global::System.ArgumentNullException(nameof(chunk));

        int count = chunk.Count;
        if (count == 0) return;

        var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(count);
        var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(count);
        var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(count);
        var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(count);
        var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(count);
        var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(count);
        var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(count);
        var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(count);

        try
        {
            if (chunk is global::System.Collections.Generic.List<ScalarMetric> listItems)
            {
                for (int i = 0; i < count; i++)
                {
                    var item = listItems[i];
                    buffer_0[i] = item.RowId;
                    buffer_1[i] = item.Flag;
                    buffer_2[i] = item.NullableFlag;
                    buffer_3[i] = (int)item.StatusCode;
                    buffer_4[i] = item.OptionalStatus is null ? (int?)null : (int)item.OptionalStatus.Value;
                    buffer_5[i] = item.TinyNum;
                    buffer_6[i] = item.ShortNum;
                    buffer_7[i] = item.FloatVal;
                }
            }
            else if (chunk is ScalarMetric[] arrayItems)
            {
                for (int i = 0; i < count; i++)
                {
                    var item = arrayItems[i];
                    buffer_0[i] = item.RowId;
                    buffer_1[i] = item.Flag;
                    buffer_2[i] = item.NullableFlag;
                    buffer_3[i] = (int)item.StatusCode;
                    buffer_4[i] = item.OptionalStatus is null ? (int?)null : (int)item.OptionalStatus.Value;
                    buffer_5[i] = item.TinyNum;
                    buffer_6[i] = item.ShortNum;
                    buffer_7[i] = item.FloatVal;
                }
            }
            else
            {
                int idx = 0;
                foreach (var item in chunk)
                {
                    buffer_0[idx] = item.RowId;
                    buffer_1[idx] = item.Flag;
                    buffer_2[idx] = item.NullableFlag;
                    buffer_3[idx] = (int)item.StatusCode;
                    buffer_4[idx] = item.OptionalStatus is null ? (int?)null : (int)item.OptionalStatus.Value;
                    buffer_5[idx] = item.TinyNum;
                    buffer_6[idx] = item.ShortNum;
                    buffer_7[idx] = item.FloatVal;
                    idx++;
                }
            }

            using (var groupWriter = writer.CreateRowGroup())
            {
                await groupWriter.WriteAsync<long>(_field_0, new global::System.ReadOnlyMemory<long>(buffer_0, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<bool>(_field_1, new global::System.ReadOnlyMemory<bool>(buffer_1, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<bool>(_field_2, new global::System.ReadOnlyMemory<bool?>(buffer_2, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<int>(_field_3, new global::System.ReadOnlyMemory<int>(buffer_3, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<int>(_field_4, new global::System.ReadOnlyMemory<int?>(buffer_4, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<byte>(_field_5, new global::System.ReadOnlyMemory<byte>(buffer_5, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<short>(_field_6, new global::System.ReadOnlyMemory<short>(buffer_6, 0, count), cancellationToken: cancellationToken);
                await groupWriter.WriteAsync<float>(_field_7, new global::System.ReadOnlyMemory<float>(buffer_7, 0, count), cancellationToken: cancellationToken);
            }
        }
        finally
        {
            global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
            global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
            global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
            global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
            global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
            global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
            global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
            global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
        }
    }

    /// <summary>
    /// Asynchronously serializes all <c>ScalarMetric</c> items using Parquet.Net low-level primitives.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetAsync(
        this global::System.Collections.Generic.IReadOnlyCollection<ScalarMetric> items,
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        cancellationToken.ThrowIfCancellationRequested();

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(Schema, stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        await writer.WriteParquetRowGroupAsync(items, cancellationToken);
    }

    /// <summary>
    /// Streams <c>ScalarMetric</c> items into a Parquet file in fixed-size row group batches using low-level primitives.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetBatchedAsync(
        this global::System.Collections.Generic.IEnumerable<ScalarMetric> items,
        global::System.IO.Stream stream,
        int? rowGroupSize = null,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        if (rowGroupSize.HasValue && rowGroupSize.Value <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(rowGroupSize));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        int targetChunkSize = rowGroupSize ?? options.RowGroupSize;
        if (targetChunkSize <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(options), "ParquetSerializerOptions.RowGroupSize must be greater than zero.");

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(Schema, stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        var buffer = new global::System.Collections.Generic.List<ScalarMetric>(targetChunkSize);
        foreach (var item in items)
        {
            cancellationToken.ThrowIfCancellationRequested();
            buffer.Add(item);
            if (buffer.Count == targetChunkSize)
            {
                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
                buffer.Clear();
            }
        }
        if (buffer.Count > 0)
            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
    }

    /// <summary>
    /// Streams <c>ScalarMetric</c> items asynchronously from an <c>IAsyncEnumerable&lt;ScalarMetric&gt;</c> sequence into a Parquet file in fixed-size row group batches.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetAsync(
        this global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> items,
        global::System.IO.Stream stream,
        int? rowGroupSize = null,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        if (rowGroupSize.HasValue && rowGroupSize.Value <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(rowGroupSize));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        int targetChunkSize = rowGroupSize ?? options.RowGroupSize;
        if (targetChunkSize <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(options), "ParquetSerializerOptions.RowGroupSize must be greater than zero.");

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(Schema, stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        var buffer = new global::System.Collections.Generic.List<ScalarMetric>(targetChunkSize);
        await foreach (var item in items)
        {
            cancellationToken.ThrowIfCancellationRequested();
            buffer.Add(item);
            if (buffer.Count == targetChunkSize)
            {
                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
                buffer.Clear();
            }
        }
        if (buffer.Count > 0)
            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects using Parquet.Net low-level primitives.
    /// Fast O(1) index-check schema resolution and ArrayPool buffer recycling.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        var results = new global::System.Collections.Generic.List<ScalarMetric>((int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount));

        var fileFields = reader.Schema.DataFields;
        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < reader.RowGroupCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(field_0, new global::System.Memory<long>(buffer_0, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_1, new global::System.Memory<bool>(buffer_1, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_2, new global::System.Memory<bool?>(buffer_2, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_3, new global::System.Memory<int>(buffer_3, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_4, new global::System.Memory<int?>(buffer_4, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(field_5, new global::System.Memory<byte>(buffer_5, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(field_6, new global::System.Memory<short>(buffer_6, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(field_7, new global::System.Memory<float>(buffer_7, 0, rowCount), cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    results.Add(new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    });
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }

        return results;
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from a Parquet stream, materialising
    /// into a single pre-sized array indexed by row-group offset rather than growing a list.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This overload reads row groups sequentially. A single <c>ParquetReader</c> over one
    /// <c>Stream</c> cannot be read concurrently — the reader seeks within the stream, so overlapping
    /// row-group reads corrupt each other — and an arbitrary <c>Stream</c> cannot be handed to more
    /// than one reader.
    /// </para>
    /// <para>
    /// For genuine decode parallelism use the <c>ReadOnlyMemory&lt;byte&gt;</c> overload, which gives
    /// every worker its own reader over its own view of the same bytes.
    /// <paramref name="maxDegreeOfParallelism"/> is not honoured here; it is accepted so that the two
    /// overloads share a signature.
    /// </para>
    /// </remarks>
    [global::System.Obsolete("Arbitrary streams cannot be read in parallel. Use ReadParquetAsync(stream) for sequential stream reading, or ReadParquetParallelAsync(ReadOnlyMemory<byte>) for true parallel decoding.")]
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetParallelAsync(
        global::System.IO.Stream stream,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        int rgCount = reader.RowGroupCount;
        if (rgCount == 0) return new global::System.Collections.Generic.List<ScalarMetric>();

        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);
        var resultArray = new ScalarMetric[totalRows];
        var rowOffsets = new int[rgCount];
        int currentOffset = 0;
        for (int r = 0; r < rgCount; r++)
        {
            rowOffsets[r] = currentOffset;
            currentOffset += (int)reader.RowGroups[r].RowCount;
        }

        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < rgCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;
            int startIdx = rowOffsets[r];

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(field_0, new global::System.Memory<long>(buffer_0, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_1, new global::System.Memory<bool>(buffer_1, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_2, new global::System.Memory<bool?>(buffer_2, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_3, new global::System.Memory<int>(buffer_3, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_4, new global::System.Memory<int?>(buffer_4, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(field_5, new global::System.Memory<byte>(buffer_5, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(field_6, new global::System.Memory<short>(buffer_6, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(field_7, new global::System.Memory<float>(buffer_7, 0, rowCount), cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    resultArray[startIdx + i] = new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }

        return new global::System.Collections.Generic.List<ScalarMetric>(resultArray);
    }

    /// <summary>
    /// Asynchronously streams <c>ScalarMetric</c> items row-group by row-group as an <see cref="global::System.Collections.Generic.IAsyncEnumerable{T}"/>.
    /// </summary>
    public static async global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> ReadParquetStreamAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(stream, BuildFormatOptions(options), cancellationToken: cancellationToken);
        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < reader.RowGroupCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(field_0, new global::System.Memory<long>(buffer_0, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_1, new global::System.Memory<bool>(buffer_1, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_2, new global::System.Memory<bool?>(buffer_2, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_3, new global::System.Memory<int>(buffer_3, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_4, new global::System.Memory<int?>(buffer_4, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(field_5, new global::System.Memory<byte>(buffer_5, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(field_6, new global::System.Memory<short>(buffer_6, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(field_7, new global::System.Memory<float>(buffer_7, 0, rowCount), cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    yield return new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects directly from an in-memory byte buffer with zero buffer allocation.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        using var stream = CreateBufferStream(parquetBytes);
        return await ReadParquetAsync(stream, options, cancellationToken);
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from an in-memory byte buffer,
    /// decoding row groups across multiple workers.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Each worker gets its own <c>ParquetReader</c> over its own stream across the same buffer, so
    /// decompression and decoding — where the cost actually is — happen concurrently. This is the
    /// reason the parallel reader is offered on a buffer and not on an arbitrary <c>Stream</c>: a
    /// single reader seeks within its stream, so overlapping row-group reads on one would corrupt
    /// each other.
    /// </para>
    /// <para>
    /// Parallelism is bounded by the row-group count — a single-row-group file has nothing to divide
    /// and reads sequentially. Row groups are claimed dynamically rather than split into fixed
    /// ranges, so uneven group sizes do not leave workers idle. Results are ordered as in the file.
    /// </para>
    /// </remarks>
    /// <param name="parquetBytes">The complete Parquet file.</param>
    /// <param name="maxDegreeOfParallelism">
    /// Maximum concurrent workers. Non-positive means unset, in which case
    /// <c>ParquetSerializerOptions.MaxDegreeOfParallelism</c> applies, and failing that
    /// <c>Environment.ProcessorCount</c>.
    /// </param>
    /// <param name="options">Serializer options, or <c>null</c> for the defaults.</param>
    /// <param name="cancellationToken">Cancels the read.</param>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetParallelAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        var formatOptions = BuildFormatOptions(options);

        var sourceBytes = global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out _)
            ? parquetBytes
            : new global::System.ReadOnlyMemory<byte>(parquetBytes.ToArray());

        int rowGroupCount;
        int totalRows = 0;
        int[] rowOffsets;
        using (var probeStream = CreateBufferStream(sourceBytes))
        {
            await using var probe = await global::Parquet.ParquetReader.CreateAsync(probeStream, formatOptions, cancellationToken: cancellationToken);
            rowGroupCount = probe.RowGroupCount;
            rowOffsets = new int[rowGroupCount];
            for (int r = 0; r < rowGroupCount; r++)
            {
                rowOffsets[r] = totalRows;
                totalRows += (int)probe.RowGroups[r].RowCount;
            }
        }

        if (rowGroupCount == 0) return new global::System.Collections.Generic.List<ScalarMetric>();

        var resultArray = new ScalarMetric[totalRows];
        var cursor = new int[1];

        int requested = maxDegreeOfParallelism > 0
            ? maxDegreeOfParallelism
            : (options.MaxDegreeOfParallelism > 0 ? options.MaxDegreeOfParallelism : global::System.Environment.ProcessorCount);
        int workerCount = global::System.Math.Max(1, global::System.Math.Min(requested, rowGroupCount));

        if (workerCount == 1)
        {
            await ReadRowGroupsIntoAsync(sourceBytes, formatOptions, resultArray, rowOffsets, cursor, rowGroupCount, cancellationToken);
        }
        else
        {
            var workers = new global::System.Threading.Tasks.Task[workerCount];
            for (int w = 0; w < workerCount; w++)
            {
                workers[w] = global::System.Threading.Tasks.Task.Run(
                    () => ReadRowGroupsIntoAsync(sourceBytes, formatOptions, resultArray, rowOffsets, cursor, rowGroupCount, cancellationToken),
                    cancellationToken);
            }

            await global::System.Threading.Tasks.Task.WhenAll(workers);
        }

        return new global::System.Collections.Generic.List<ScalarMetric>(resultArray);
    }

    /// <summary>
    /// One parallel-read worker: opens its own reader over the shared buffer and materialises every
    /// row group it manages to claim.
    /// </summary>
    /// <remarks>
    /// Workers write into disjoint index ranges of <paramref name="target"/> — a row group's rows
    /// start at its precomputed offset — so no synchronisation is needed beyond claiming the group.
    /// </remarks>
    private static async global::System.Threading.Tasks.Task ReadRowGroupsIntoAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.ParquetOptions formatOptions,
        ScalarMetric[] target,
        int[] rowOffsets,
        int[] cursor,
        int rowGroupCount,
        global::System.Threading.CancellationToken cancellationToken)
    {
        using var stream = CreateBufferStream(parquetBytes);
        await using var reader = await global::Parquet.ParquetReader.CreateAsync(stream, formatOptions, cancellationToken: cancellationToken);

        var fileFields = reader.Schema.DataFields;
        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        while (true)
        {
            int r = global::System.Threading.Interlocked.Increment(ref cursor[0]) - 1;
            if (r >= rowGroupCount) break;

            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;
            int startIdx = rowOffsets[r];

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(field_0, new global::System.Memory<long>(buffer_0, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_1, new global::System.Memory<bool>(buffer_1, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(field_2, new global::System.Memory<bool?>(buffer_2, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_3, new global::System.Memory<int>(buffer_3, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(field_4, new global::System.Memory<int?>(buffer_4, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(field_5, new global::System.Memory<byte>(buffer_5, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(field_6, new global::System.Memory<short>(buffer_6, 0, rowCount), cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(field_7, new global::System.Memory<float>(buffer_7, 0, rowCount), cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    target[startIdx + i] = new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }
    }

    /// <summary>
    /// Asynchronously streams <c>ScalarMetric</c> items from an in-memory byte buffer, row group by row group.
    /// </summary>
    public static async global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> ReadParquetStreamAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)
    {
        using var stream = CreateBufferStream(parquetBytes);
        await foreach (var item in ReadParquetStreamAsync(stream, options, cancellationToken))
        {
            yield return item;
        }
    }

    /// <summary>
    /// Wraps a byte buffer as a read-only stream, without copying where the buffer is array-backed.
    /// </summary>
    /// <remarks>
    /// Each call returns an independent stream over the same bytes, which is what makes the parallel
    /// reader possible: every worker gets its own cursor without copying the file.
    /// </remarks>
    private static global::System.IO.MemoryStream CreateBufferStream(global::System.ReadOnlyMemory<byte> parquetBytes)
    {
        return global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out var segment)
            ? new global::System.IO.MemoryStream(segment.Array!, segment.Offset, segment.Count, writable: false)
            : new global::System.IO.MemoryStream(parquetBytes.ToArray(), writable: false);
    }
}
