// <auto-generated />
#nullable enable
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629

namespace SampleDomain.Models;

public static partial class ScalarMetricParquetExtensions
{
    /// <summary>
    /// Static compile-time <c>Parquet.Schema.ParquetSchema</c> for <c>ScalarMetric</c>.
    /// </summary>
    public static readonly global::Parquet.Schema.ParquetSchema Schema = new global::Parquet.Schema.ParquetSchema(
        new global::Parquet.Schema.DataField("row_id", typeof(long), isNullable: false),
        new global::Parquet.Schema.DataField("is_valid", typeof(bool), isNullable: false),
        new global::Parquet.Schema.DataField("maybe_flag", typeof(bool), isNullable: true),
        new global::Parquet.Schema.DataField("status", typeof(int), isNullable: false),
        new global::Parquet.Schema.DataField("opt_status", typeof(int), isNullable: true),
        new global::Parquet.Schema.DataField("tiny_num", typeof(byte), isNullable: false),
        new global::Parquet.Schema.DataField("short_num", typeof(short), isNullable: false),
        new global::Parquet.Schema.DataField("float_val", typeof(float), isNullable: false)
    );

    private static readonly global::Parquet.Schema.DataField _field_0 = (global::Parquet.Schema.DataField)Schema.Fields[0];
    private static readonly global::Parquet.Schema.DataField _field_1 = (global::Parquet.Schema.DataField)Schema.Fields[1];
    private static readonly global::Parquet.Schema.DataField _field_2 = (global::Parquet.Schema.DataField)Schema.Fields[2];
    private static readonly global::Parquet.Schema.DataField _field_3 = (global::Parquet.Schema.DataField)Schema.Fields[3];
    private static readonly global::Parquet.Schema.DataField _field_4 = (global::Parquet.Schema.DataField)Schema.Fields[4];
    private static readonly global::Parquet.Schema.DataField _field_5 = (global::Parquet.Schema.DataField)Schema.Fields[5];
    private static readonly global::Parquet.Schema.DataField _field_6 = (global::Parquet.Schema.DataField)Schema.Fields[6];
    private static readonly global::Parquet.Schema.DataField _field_7 = (global::Parquet.Schema.DataField)Schema.Fields[7];

    /// <summary>
    /// Resolves one generated schema field against the fields actually present in the file.
    /// </summary>
    private static global::Parquet.Schema.DataField ResolveSchemaField(
        global::Parquet.Schema.DataField[] fileFields,
        int index,
        global::Parquet.Schema.DataField expected,
        ref global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? byName)
    {
        // Ordered schemas resolve on a single index check: no hashing, no delegate, no allocation.
        // Every file this generator writes lands here, as does any file whose column order matches.
        if ((uint)index < (uint)fileFields.Length
            && string.Equals(fileFields[index].Name, expected.Name, global::System.StringComparison.OrdinalIgnoreCase))
        {
            return fileFields[index];
        }

        // Only a file whose column order differs reaches here. The name index is built at most once
        // per read and reused for every subsequent miss, so even a fully reordered schema costs O(n)
        // in total rather than a linear scan per field.
        if (byName is null)
        {
            byName = new global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>(
                fileFields.Length, global::System.StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < fileFields.Length; i++)
            {
                // First occurrence wins if a file carries duplicate column names. Dictionary.TryAdd is
                // not available to netstandard2.0 consumers, hence the explicit containment check.
                if (!byName.ContainsKey(fileFields[i].Name))
                {
                    byName.Add(fileFields[i].Name, fileFields[i]);
                }
            }
        }

        if (byName.TryGetValue(expected.Name, out var match))
        {
            return match;
        }

        if (!expected.IsNullable)
        {
            throw new global::System.IO.InvalidDataException($"Required column '{expected.Name}' was not found in the Parquet file schema.");
        }

        return expected;
    }

    /// <summary>
    /// Translates the generator's options into the Parquet.Net options the writer accepts.
    /// </summary>
    private static global::Parquet.ParquetOptions BuildFormatOptions(global::Parquet.SourceGenerator.ParquetSerializerOptions options)
    {
        var formatOptions = new global::Parquet.ParquetOptions
        {
            CompressionMethod = options.CompressionMethod switch
            {
                global::Parquet.SourceGenerator.ParquetCompressionMethod.None =>
                    global::Parquet.CompressionMethod.None,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Gzip =>
                    global::Parquet.CompressionMethod.Gzip,
                // Parquet.Net spells this one in caps.
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Lz4 =>
                    global::Parquet.CompressionMethod.LZ4,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Brotli =>
                    global::Parquet.CompressionMethod.Brotli,
                global::Parquet.SourceGenerator.ParquetCompressionMethod.Zstd =>
                    global::Parquet.CompressionMethod.Zstd,
                _ => global::Parquet.CompressionMethod.Snappy,
            },
        };

        if (options.CompressionLevel.HasValue)
        {
            formatOptions.CompressionLevel = options.CompressionLevel.Value switch
            {
                global::Parquet.SourceGenerator.ParquetCompressionLevel.Optimal =>
                    global::System.IO.Compression.CompressionLevel.Optimal,
                global::Parquet.SourceGenerator.ParquetCompressionLevel.Fastest =>
                    global::System.IO.Compression.CompressionLevel.Fastest,
                global::Parquet.SourceGenerator.ParquetCompressionLevel.NoCompression =>
                    global::System.IO.Compression.CompressionLevel.NoCompression,
                _ => global::System.IO.Compression.CompressionLevel.SmallestSize,
            };
        }

        if (options.DictionaryEncodingThreshold.HasValue)
        {
            formatOptions.DictionaryEncodingThreshold = options.DictionaryEncodingThreshold.Value;
        }

        if (options.DictionaryEncodingSampleSize.HasValue)
        {
            formatOptions.DictionaryEncodingSampleSize = options.DictionaryEncodingSampleSize.Value;
        }

        foreach (var kvp in options.ColumnEncodingHints)
        {
            formatOptions.ColumnEncodingHints[kvp.Key] = kvp.Value switch
            {
                global::Parquet.SourceGenerator.ParquetColumnEncoding.Dictionary =>
                    global::Parquet.EncodingHint.Dictionary,
                global::Parquet.SourceGenerator.ParquetColumnEncoding.DeltaBinaryPacked =>
                    global::Parquet.EncodingHint.DeltaBinaryPacked,
                global::Parquet.SourceGenerator.ParquetColumnEncoding.ByteSplitStream =>
                    global::Parquet.EncodingHint.ByteSplitStream,
                _ => global::Parquet.EncodingHint.Default,
            };
        }

        return formatOptions;
    }

    /// <summary>
    /// Writes a single row group chunk using Parquet.Net low-level primitives for maximum speed and Native AOT compatibility.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetRowGroupAsync(
        this global::Parquet.ParquetWriter writer,
        global::System.Collections.Generic.IReadOnlyCollection<ScalarMetric> chunk,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (writer == null) throw new global::System.ArgumentNullException(nameof(writer));
        if (chunk == null) throw new global::System.ArgumentNullException(nameof(chunk));

        int count = chunk.Count;
        if (count == 0) return;

        var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(count);
        var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(count);
        var buffer_2 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(count);
        var defLevels_2 = global::System.Buffers.ArrayPool<int>.Shared.Rent(count);
        int nonNullCount_2 = 0;
        var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(count);
        var buffer_4 = global::System.Buffers.ArrayPool<int>.Shared.Rent(count);
        var defLevels_4 = global::System.Buffers.ArrayPool<int>.Shared.Rent(count);
        int nonNullCount_4 = 0;
        var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(count);
        var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(count);
        var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(count);

        try
        {
            if (chunk is global::System.Collections.Generic.List<ScalarMetric> listItems)
            {
#if NET6_0_OR_GREATER
                void ExtractSpan()
                {
                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(listItems);
                    ref var srcRef_ = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(span);
                    ref var dstRef_0 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_0);
                    ref var dstRef_1 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_1);
                    ref var dstRef_2 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_2);
                    ref var defRef_2 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(defLevels_2);
                    ref var dstRef_3 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_3);
                    ref var dstRef_4 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_4);
                    ref var defRef_4 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(defLevels_4);
                    ref var dstRef_5 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_5);
                    ref var dstRef_6 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_6);
                    ref var dstRef_7 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_7);
                    for (int i = 0; i < count; i++)
                    {
                        ref readonly var item = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref srcRef_, i);
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_0, i) = item.RowId;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_1, i) = item.Flag;
                        var val_2 = item.NullableFlag;
                        if (val_2.HasValue)
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_2, nonNullCount_2++) = val_2.Value;
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_2, i) = 1;
                        }
                        else
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_2, i) = 0;
                        }
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_3, i) = (int)item.StatusCode;
                        var val_4 = item.OptionalStatus;
                        if (val_4.HasValue)
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_4, nonNullCount_4++) = (int)val_4.Value;
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_4, i) = 1;
                        }
                        else
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_4, i) = 0;
                        }
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_5, i) = item.TinyNum;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_6, i) = item.ShortNum;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_7, i) = item.FloatVal;
                    }
                }
                ExtractSpan();
#else
                for (int i = 0; i < count; i++)
                {
                    var item = listItems[i];
                    buffer_0[i] = item.RowId;
                    buffer_1[i] = item.Flag;
                    var val_2 = item.NullableFlag;
                    if (val_2.HasValue)
                    {
                        buffer_2[nonNullCount_2++] = val_2.Value;
                        defLevels_2[i] = 1;
                    }
                    else
                    {
                        defLevels_2[i] = 0;
                    }
                    buffer_3[i] = (int)item.StatusCode;
                    var val_4 = item.OptionalStatus;
                    if (val_4.HasValue)
                    {
                        buffer_4[nonNullCount_4++] = (int)val_4.Value;
                        defLevels_4[i] = 1;
                    }
                    else
                    {
                        defLevels_4[i] = 0;
                    }
                    buffer_5[i] = item.TinyNum;
                    buffer_6[i] = item.ShortNum;
                    buffer_7[i] = item.FloatVal;
                }
#endif
            }
            else if (chunk is ScalarMetric[] arrayItems)
            {
#if NET6_0_OR_GREATER
                void ExtractArray()
                {
                    ref var srcRef_ = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(arrayItems);
                    ref var dstRef_0 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_0);
                    ref var dstRef_1 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_1);
                    ref var dstRef_2 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_2);
                    ref var defRef_2 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(defLevels_2);
                    ref var dstRef_3 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_3);
                    ref var dstRef_4 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_4);
                    ref var defRef_4 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(defLevels_4);
                    ref var dstRef_5 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_5);
                    ref var dstRef_6 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_6);
                    ref var dstRef_7 = ref global::System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(buffer_7);
                    for (int i = 0; i < count; i++)
                    {
                        ref readonly var item = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref srcRef_, i);
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_0, i) = item.RowId;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_1, i) = item.Flag;
                        var val_2 = item.NullableFlag;
                        if (val_2.HasValue)
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_2, nonNullCount_2++) = val_2.Value;
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_2, i) = 1;
                        }
                        else
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_2, i) = 0;
                        }
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_3, i) = (int)item.StatusCode;
                        var val_4 = item.OptionalStatus;
                        if (val_4.HasValue)
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_4, nonNullCount_4++) = (int)val_4.Value;
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_4, i) = 1;
                        }
                        else
                        {
                            global::System.Runtime.CompilerServices.Unsafe.Add(ref defRef_4, i) = 0;
                        }
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_5, i) = item.TinyNum;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_6, i) = item.ShortNum;
                        global::System.Runtime.CompilerServices.Unsafe.Add(ref dstRef_7, i) = item.FloatVal;
                    }
                }
                ExtractArray();
#else
                for (int i = 0; i < count; i++)
                {
                    var item = arrayItems[i];
                    buffer_0[i] = item.RowId;
                    buffer_1[i] = item.Flag;
                    var val_2 = item.NullableFlag;
                    if (val_2.HasValue)
                    {
                        buffer_2[nonNullCount_2++] = val_2.Value;
                        defLevels_2[i] = 1;
                    }
                    else
                    {
                        defLevels_2[i] = 0;
                    }
                    buffer_3[i] = (int)item.StatusCode;
                    var val_4 = item.OptionalStatus;
                    if (val_4.HasValue)
                    {
                        buffer_4[nonNullCount_4++] = (int)val_4.Value;
                        defLevels_4[i] = 1;
                    }
                    else
                    {
                        defLevels_4[i] = 0;
                    }
                    buffer_5[i] = item.TinyNum;
                    buffer_6[i] = item.ShortNum;
                    buffer_7[i] = item.FloatVal;
                }
#endif
            }
            else
            {
                int idx = 0;
                foreach (var item in chunk)
                {
                    buffer_0[idx] = item.RowId;
                    buffer_1[idx] = item.Flag;
                    var val_2 = item.NullableFlag;
                    if (val_2.HasValue)
                    {
                        buffer_2[nonNullCount_2++] = val_2.Value;
                        defLevels_2[idx] = 1;
                    }
                    else
                    {
                        defLevels_2[idx] = 0;
                    }
                    buffer_3[idx] = (int)item.StatusCode;
                    var val_4 = item.OptionalStatus;
                    if (val_4.HasValue)
                    {
                        buffer_4[nonNullCount_4++] = (int)val_4.Value;
                        defLevels_4[idx] = 1;
                    }
                    else
                    {
                        defLevels_4[idx] = 0;
                    }
                    buffer_5[idx] = item.TinyNum;
                    buffer_6[idx] = item.ShortNum;
                    buffer_7[idx] = item.FloatVal;
                    idx++;
                }
            }

            using (var groupWriter = writer.CreateRowGroup())
            {
                await groupWriter.WriteAsync<long>(
                    _field_0,
                    new global::System.ReadOnlyMemory<long>(buffer_0, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                buffer_0 = null!;
                await groupWriter.WriteAsync<bool>(
                    _field_1,
                    new global::System.ReadOnlyMemory<bool>(buffer_1, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                buffer_1 = null!;
                await groupWriter.WriteAllPartsAsync<bool>(
                    _field_2,
                    new global::System.ReadOnlyMemory<bool>(buffer_2, 0, nonNullCount_2),
                    new global::System.ReadOnlyMemory<int>(defLevels_2, 0, count),
                    null,
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_2, clearArray: false);
                buffer_2 = null!;
                global::System.Buffers.ArrayPool<int>.Shared.Return(defLevels_2, clearArray: false);
                defLevels_2 = null!;
                await groupWriter.WriteAsync<int>(
                    _field_3,
                    new global::System.ReadOnlyMemory<int>(buffer_3, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                buffer_3 = null!;
                await groupWriter.WriteAllPartsAsync<int>(
                    _field_4,
                    new global::System.ReadOnlyMemory<int>(buffer_4, 0, nonNullCount_4),
                    new global::System.ReadOnlyMemory<int>(defLevels_4, 0, count),
                    null,
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_4, clearArray: false);
                buffer_4 = null!;
                global::System.Buffers.ArrayPool<int>.Shared.Return(defLevels_4, clearArray: false);
                defLevels_4 = null!;
                await groupWriter.WriteAsync<byte>(
                    _field_5,
                    new global::System.ReadOnlyMemory<byte>(buffer_5, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                buffer_5 = null!;
                await groupWriter.WriteAsync<short>(
                    _field_6,
                    new global::System.ReadOnlyMemory<short>(buffer_6, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                buffer_6 = null!;
                await groupWriter.WriteAsync<float>(
                    _field_7,
                    new global::System.ReadOnlyMemory<float>(buffer_7, 0, count),
                    cancellationToken: cancellationToken);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
                buffer_7 = null!;
            }
        }
        finally
        {
            if (buffer_0 != null) global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
            if (buffer_1 != null) global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
            if (buffer_2 != null) global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_2, clearArray: false);
            if (defLevels_2 != null) global::System.Buffers.ArrayPool<int>.Shared.Return(defLevels_2, clearArray: false);
            if (buffer_3 != null) global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
            if (buffer_4 != null) global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_4, clearArray: false);
            if (defLevels_4 != null) global::System.Buffers.ArrayPool<int>.Shared.Return(defLevels_4, clearArray: false);
            if (buffer_5 != null) global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
            if (buffer_6 != null) global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
            if (buffer_7 != null) global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
        }
    }

    /// <summary>
    /// Asynchronously serializes all <c>ScalarMetric</c> items using Parquet.Net low-level primitives.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetAsync(
        this global::System.Collections.Generic.IReadOnlyCollection<ScalarMetric> items,
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        cancellationToken.ThrowIfCancellationRequested();

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(
            Schema,
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        await writer.WriteParquetRowGroupAsync(items, cancellationToken);
    }

    /// <summary>
    /// Streams <c>ScalarMetric</c> items into a Parquet file in fixed-size row group batches using low-level primitives.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetBatchedAsync(
        this global::System.Collections.Generic.IEnumerable<ScalarMetric> items,
        global::System.IO.Stream stream,
        int? rowGroupSize = null,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        if (rowGroupSize.HasValue && rowGroupSize.Value <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(rowGroupSize));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        int targetChunkSize = rowGroupSize ?? options.RowGroupSize;
        if (targetChunkSize <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(options), "ParquetSerializerOptions.RowGroupSize must be greater than zero.");

        if (items is global::System.Collections.Generic.IReadOnlyCollection<ScalarMetric> col && col.Count <= targetChunkSize)
        {
            await using var singleWriter = await global::Parquet.ParquetWriter.CreateAsync(
                Schema,
                stream,
                BuildFormatOptions(options),
                cancellationToken: cancellationToken);
            await singleWriter.WriteParquetRowGroupAsync(col, cancellationToken);
            return;
        }

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(
            Schema,
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        var buffer = new global::System.Collections.Generic.List<ScalarMetric>(targetChunkSize);
        foreach (var item in items)
        {
            cancellationToken.ThrowIfCancellationRequested();
            buffer.Add(item);
            if (buffer.Count == targetChunkSize)
            {
                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
                buffer.Clear();
            }
        }
        if (buffer.Count > 0)
            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
    }

    /// <summary>
    /// Streams <c>ScalarMetric</c> items asynchronously from an <c>IAsyncEnumerable&lt;ScalarMetric&gt;</c> sequence into a Parquet file in fixed-size row group batches.
    /// </summary>
    public static async global::System.Threading.Tasks.Task WriteParquetAsync(
        this global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> items,
        global::System.IO.Stream stream,
        int? rowGroupSize = null,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (items == null) throw new global::System.ArgumentNullException(nameof(items));
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));
        if (rowGroupSize.HasValue && rowGroupSize.Value <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(rowGroupSize));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        int targetChunkSize = rowGroupSize ?? options.RowGroupSize;
        if (targetChunkSize <= 0)
            throw new global::System.ArgumentOutOfRangeException(nameof(options), "ParquetSerializerOptions.RowGroupSize must be greater than zero.");

        await using var writer = await global::Parquet.ParquetWriter.CreateAsync(
            Schema,
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        var buffer = new global::System.Collections.Generic.List<ScalarMetric>(targetChunkSize);
        await foreach (var item in items)
        {
            cancellationToken.ThrowIfCancellationRequested();
            buffer.Add(item);
            if (buffer.Count == targetChunkSize)
            {
                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
                buffer.Clear();
            }
        }
        if (buffer.Count > 0)
            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects using Parquet.Net low-level primitives.
    /// Fast O(1) index-check schema resolution and ArrayPool buffer recycling.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);
#if NET8_0_OR_GREATER
        var results = new global::System.Collections.Generic.List<ScalarMetric>(totalRows);
        global::System.Runtime.InteropServices.CollectionsMarshal.SetCount(results, totalRows);
#else
        var results = new global::System.Collections.Generic.List<ScalarMetric>(totalRows);
#endif
        int currentOffset = 0;

        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < reader.RowGroupCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(
                    field_0,
                    new global::System.Memory<long>(buffer_0, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_1,
                    new global::System.Memory<bool>(buffer_1, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_2,
                    new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_3,
                    new global::System.Memory<int>(buffer_3, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_4,
                    new global::System.Memory<int?>(buffer_4, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(
                    field_5,
                    new global::System.Memory<byte>(buffer_5, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(
                    field_6,
                    new global::System.Memory<short>(buffer_6, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(
                    field_7,
                    new global::System.Memory<float>(buffer_7, 0, rowCount),
                    cancellationToken: cancellationToken);

#if NET8_0_OR_GREATER
                void PopulateSpan()
                {
                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(results);
                    for (int i = 0; i < rowCount; i++)
                    {
                        span[currentOffset + i] = new ScalarMetric
                        {
                            RowId = buffer_0[i],
                            Flag = buffer_1[i],
                            NullableFlag = buffer_2[i],
                            StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                            OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                            TinyNum = buffer_5[i],
                            ShortNum = buffer_6[i],
                            FloatVal = buffer_7[i],
                        };
                    }
                }
                PopulateSpan();
#else
                for (int i = 0; i < rowCount; i++)
                {
                    results.Add(new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    });
                }
#endif
                currentOffset += rowCount;
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }

        return results;
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects directly into an array using Parquet.Net low-level primitives.
    /// Eliminates List wrapper allocations for zero-copy array materialization.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<ScalarMetric[]> ReadParquetArrayAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);
        var results = new ScalarMetric[totalRows];
        int currentOffset = 0;

        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < reader.RowGroupCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(
                    field_0,
                    new global::System.Memory<long>(buffer_0, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_1,
                    new global::System.Memory<bool>(buffer_1, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_2,
                    new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_3,
                    new global::System.Memory<int>(buffer_3, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_4,
                    new global::System.Memory<int?>(buffer_4, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(
                    field_5,
                    new global::System.Memory<byte>(buffer_5, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(
                    field_6,
                    new global::System.Memory<short>(buffer_6, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(
                    field_7,
                    new global::System.Memory<float>(buffer_7, 0, rowCount),
                    cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    results[currentOffset + i] = new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
                currentOffset += rowCount;
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }

        return results;
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from a Parquet stream directly into an array.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This overload reads row groups sequentially. A single <c>ParquetReader</c> over one
    /// <c>Stream</c> cannot be read concurrently — the reader seeks within the stream, so overlapping
    /// row-group reads corrupt each other — and an arbitrary <c>Stream</c> cannot be handed to more
    /// than one reader.
    /// </para>
    /// <para>
    /// For genuine decode parallelism use the <c>ReadOnlyMemory&lt;byte&gt;</c> overload, which gives
    /// every worker its own reader over its own view of the same bytes.
    /// </para>
    /// </remarks>
    public static async global::System.Threading.Tasks.Task<ScalarMetric[]> ReadParquetParallelArrayAsync(
        global::System.IO.Stream stream,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        int rgCount = reader.RowGroupCount;
        if (rgCount == 0) return global::System.Array.Empty<ScalarMetric>();

        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);
        var resultArray = new ScalarMetric[totalRows];
        var rowOffsets = new int[rgCount];
        int currentOffset = 0;
        for (int r = 0; r < rgCount; r++)
        {
            rowOffsets[r] = currentOffset;
            currentOffset += (int)reader.RowGroups[r].RowCount;
        }

        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < rgCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;
            int startIdx = rowOffsets[r];

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);

            try
            {
                await groupReader.ReadAsync<long>(
                    field_0,
                    new global::System.Memory<long>(buffer_0, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_1,
                    new global::System.Memory<bool>(buffer_1, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_2,
                    new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_3,
                    new global::System.Memory<int>(buffer_3, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_4,
                    new global::System.Memory<int?>(buffer_4, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(
                    field_5,
                    new global::System.Memory<byte>(buffer_5, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(
                    field_6,
                    new global::System.Memory<short>(buffer_6, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(
                    field_7,
                    new global::System.Memory<float>(buffer_7, 0, rowCount),
                    cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    resultArray[startIdx + i] = new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }

        return resultArray;
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from a Parquet stream, materialising
    /// into a single pre-sized list indexed by row-group offset rather than growing a list.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetParallelAsync(
        global::System.IO.Stream stream,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var resultArray = await ReadParquetParallelArrayAsync(stream, maxDegreeOfParallelism, options, cancellationToken);
        return new global::System.Collections.Generic.List<ScalarMetric>(resultArray);
    }

    /// <summary>
    /// Asynchronously streams <c>ScalarMetric</c> items row-group by row-group as an <see cref="global::System.Collections.Generic.IAsyncEnumerable{T}"/>.
    /// Memory usage is bounded by a single row group rather than the whole file.
    /// </summary>
    public static async global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> ReadParquetStreamAsync(
        global::System.IO.Stream stream,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));

        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;

        await using var reader = await global::Parquet.ParquetReader.CreateAsync(
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        var fileFields = reader.Schema.DataFields;

        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        for (int r = 0; r < reader.RowGroupCount; r++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var groupReader = reader.OpenRowGroupReader(r);
            int rowCount = (int)groupReader.RowCount;

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(rowCount);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(rowCount);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(rowCount);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(rowCount);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(rowCount);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(rowCount);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(rowCount);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(rowCount);
            try
            {
                await groupReader.ReadAsync<long>(
                    field_0,
                    new global::System.Memory<long>(buffer_0, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_1,
                    new global::System.Memory<bool>(buffer_1, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_2,
                    new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_3,
                    new global::System.Memory<int>(buffer_3, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_4,
                    new global::System.Memory<int?>(buffer_4, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(
                    field_5,
                    new global::System.Memory<byte>(buffer_5, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(
                    field_6,
                    new global::System.Memory<short>(buffer_6, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(
                    field_7,
                    new global::System.Memory<float>(buffer_7, 0, rowCount),
                    cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    yield return new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects directly from an in-memory byte buffer with zero buffer allocation.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var results = await ReadBufferSequentialArrayAsync(parquetBytes, options, cancellationToken);
        return new global::System.Collections.Generic.List<ScalarMetric>(results);
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects directly from an in-memory byte buffer into an array with zero buffer allocation.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<ScalarMetric[]> ReadParquetArrayAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        return await ReadBufferSequentialArrayAsync(parquetBytes, options, cancellationToken);
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from an in-memory byte buffer into an array,
    /// decoding row groups across multiple workers with zero list wrapper allocation.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<ScalarMetric[]> ReadParquetParallelArrayAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        var formatOptions = BuildFormatOptions(options);

        var sourceBytes = global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out _)
            ? parquetBytes
            : new global::System.ReadOnlyMemory<byte>(parquetBytes.ToArray());

        int rowGroupCount;
        int totalRows;
        int maxRowGroupSize;
        int[] rowOffsets;
        using (var probeStream = CreateBufferStream(sourceBytes))
        {
            await using var probe = await global::Parquet.ParquetReader.CreateAsync(
                probeStream,
                formatOptions,
                cancellationToken: cancellationToken);
            rowGroupCount = probe.RowGroupCount;
            totalRows = 0;
            maxRowGroupSize = 0;
            rowOffsets = new int[rowGroupCount];
            for (int r = 0; r < rowGroupCount; r++)
            {
                int rc = (int)probe.RowGroups[r].RowCount;
                rowOffsets[r] = totalRows;
                totalRows += rc;
                if (rc > maxRowGroupSize) maxRowGroupSize = rc;
            }
        }

        if (rowGroupCount == 0) return global::System.Array.Empty<ScalarMetric>();

        // Small row count or single row group fast path: drop to sequential reader
        if (rowGroupCount <= 1 || totalRows <= 10_000)
        {
            return await ReadBufferSequentialArrayAsync(sourceBytes, options, cancellationToken);
        }

        var resultArray = new ScalarMetric[totalRows];
        using var linkedCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        var workerToken = linkedCts.Token;
        var cursor = new int[1];

        int requested = maxDegreeOfParallelism > 0
            ? maxDegreeOfParallelism
            : (options.MaxDegreeOfParallelism > 0 ? options.MaxDegreeOfParallelism : global::System.Environment.ProcessorCount);
        int workerCount = global::System.Math.Max(1, global::System.Math.Min(requested, rowGroupCount));

        if (workerCount == 1)
        {
            await ReadRowGroupsIntoAsync(sourceBytes,
                formatOptions,
                resultArray,
                rowOffsets,
                cursor,
                rowGroupCount,
                maxRowGroupSize,
                linkedCts,
                workerToken);
        }
        else
        {
            var workers = new global::System.Threading.Tasks.Task[workerCount];
            for (int w = 0; w < workerCount; w++)
            {
                workers[w] = global::System.Threading.Tasks.Task.Run(
                    () => ReadRowGroupsIntoAsync(sourceBytes,
                        formatOptions,
                        resultArray,
                        rowOffsets,
                        cursor,
                        rowGroupCount,
                        maxRowGroupSize,
                        linkedCts,
                        workerToken),
                    workerToken);
            }

            try
            {
                await global::System.Threading.Tasks.Task.WhenAll(workers);
            }
            catch
            {
                linkedCts.Cancel();
                throw;
            }
        }

        return resultArray;
    }

    /// <summary>
    /// Asynchronously deserializes all <c>ScalarMetric</c> objects from an in-memory byte buffer,
    /// decoding row groups across multiple workers.
    /// </summary>
    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<ScalarMetric>> ReadParquetParallelAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        int maxDegreeOfParallelism = -1,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var resultArray = await ReadParquetParallelArrayAsync(parquetBytes, maxDegreeOfParallelism, options, cancellationToken);
        return new global::System.Collections.Generic.List<ScalarMetric>(resultArray);
    }

    /// <summary>
    /// One parallel-read worker: opens its own reader over the shared buffer and materialises every
    /// row group it manages to claim.
    /// </summary>
    /// <remarks>
    /// Workers write into disjoint index ranges of <paramref name="target"/> — a row group's rows
    /// start at its precomputed offset — so no synchronisation is needed beyond claiming the group.
    /// </remarks>
    private static async global::System.Threading.Tasks.Task ReadRowGroupsIntoAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.ParquetOptions formatOptions,
        ScalarMetric[] target,
        int[] rowOffsets,
        int[] cursor,
        int rowGroupCount,
        int maxRowGroupSize,
        global::System.Threading.CancellationTokenSource linkedCts,
        global::System.Threading.CancellationToken cancellationToken)
    {
        try
        {
            using var stream = CreateBufferStream(parquetBytes);
            await using var reader = await global::Parquet.ParquetReader.CreateAsync(
                stream,
                formatOptions,
                cancellationToken: cancellationToken);

            var fileFields = reader.Schema.DataFields;

            global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;
            var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
            var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
            var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
            var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
            var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
            var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
            var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
            var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

            var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(maxRowGroupSize);
            var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(maxRowGroupSize);
            var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(maxRowGroupSize);
            var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(maxRowGroupSize);
            var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(maxRowGroupSize);
            var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(maxRowGroupSize);
            var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(maxRowGroupSize);
            var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(maxRowGroupSize);

            try
            {
                while (true)
                {
                    int r = global::System.Threading.Interlocked.Increment(ref cursor[0]) - 1;
                    if (r >= rowGroupCount) break;

                    cancellationToken.ThrowIfCancellationRequested();
                    using var groupReader = reader.OpenRowGroupReader(r);
                    int rowCount = (int)groupReader.RowCount;
                    int startIdx = rowOffsets[r];

                    await groupReader.ReadAsync<long>(
                        field_0,
                        new global::System.Memory<long>(buffer_0, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<bool>(
                        field_1,
                        new global::System.Memory<bool>(buffer_1, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<bool>(
                        field_2,
                        new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<int>(
                        field_3,
                        new global::System.Memory<int>(buffer_3, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<int>(
                        field_4,
                        new global::System.Memory<int?>(buffer_4, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<byte>(
                        field_5,
                        new global::System.Memory<byte>(buffer_5, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<short>(
                        field_6,
                        new global::System.Memory<short>(buffer_6, 0, rowCount),
                        cancellationToken: cancellationToken);
                    await groupReader.ReadAsync<float>(
                        field_7,
                        new global::System.Memory<float>(buffer_7, 0, rowCount),
                        cancellationToken: cancellationToken);

                    for (int i = 0; i < rowCount; i++)
                    {
                        target[startIdx + i] = new ScalarMetric
                        {
                            RowId = buffer_0[i],
                            Flag = buffer_1[i],
                            NullableFlag = buffer_2[i],
                            StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                            OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                            TinyNum = buffer_5[i],
                            ShortNum = buffer_6[i],
                            FloatVal = buffer_7[i],
                        };
                    }
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
                global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
                global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
                global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
                global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
                global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
                global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
            }
        }
        catch
        {
            linkedCts.Cancel();
            throw;
        }
    }

    /// <summary>
    /// Dedicated sequential reader over an in-memory buffer without threadpool hops or stream wrapping overhead.
    /// </summary>
    private static async global::System.Threading.Tasks.Task<ScalarMetric[]> ReadBufferSequentialArrayAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;
        using var stream = CreateBufferStream(parquetBytes);
        await using var reader = await global::Parquet.ParquetReader.CreateAsync(
            stream,
            BuildFormatOptions(options),
            cancellationToken: cancellationToken);
        int rowGroupCount = reader.RowGroupCount;
        if (rowGroupCount == 0) return global::System.Array.Empty<ScalarMetric>();

        int totalRows = 0;
        int maxRowCount = 0;
        for (int r = 0; r < rowGroupCount; r++)
        {
            int rc = (int)reader.RowGroups[r].RowCount;
            totalRows += rc;
            if (rc > maxRowCount) maxRowCount = rc;
        }

        var results = new ScalarMetric[totalRows];
        int currentOffset = 0;
        var fileFields = reader.Schema.DataFields;
        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;

        var field_0 = ResolveSchemaField(fileFields, 0, _field_0, ref fieldsByName);
        var field_1 = ResolveSchemaField(fileFields, 1, _field_1, ref fieldsByName);
        var field_2 = ResolveSchemaField(fileFields, 2, _field_2, ref fieldsByName);
        var field_3 = ResolveSchemaField(fileFields, 3, _field_3, ref fieldsByName);
        var field_4 = ResolveSchemaField(fileFields, 4, _field_4, ref fieldsByName);
        var field_5 = ResolveSchemaField(fileFields, 5, _field_5, ref fieldsByName);
        var field_6 = ResolveSchemaField(fileFields, 6, _field_6, ref fieldsByName);
        var field_7 = ResolveSchemaField(fileFields, 7, _field_7, ref fieldsByName);

        var buffer_0 = global::System.Buffers.ArrayPool<long>.Shared.Rent(maxRowCount);
        var buffer_1 = global::System.Buffers.ArrayPool<bool>.Shared.Rent(maxRowCount);
        var buffer_2 = global::System.Buffers.ArrayPool<bool?>.Shared.Rent(maxRowCount);
        var buffer_3 = global::System.Buffers.ArrayPool<int>.Shared.Rent(maxRowCount);
        var buffer_4 = global::System.Buffers.ArrayPool<int?>.Shared.Rent(maxRowCount);
        var buffer_5 = global::System.Buffers.ArrayPool<byte>.Shared.Rent(maxRowCount);
        var buffer_6 = global::System.Buffers.ArrayPool<short>.Shared.Rent(maxRowCount);
        var buffer_7 = global::System.Buffers.ArrayPool<float>.Shared.Rent(maxRowCount);

        try
        {
            for (int r = 0; r < rowGroupCount; r++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                using var groupReader = reader.OpenRowGroupReader(r);
                int rowCount = (int)groupReader.RowCount;
                if (rowCount == 0) continue;

                await groupReader.ReadAsync<long>(
                    field_0,
                    new global::System.Memory<long>(buffer_0, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_1,
                    new global::System.Memory<bool>(buffer_1, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<bool>(
                    field_2,
                    new global::System.Memory<bool?>(buffer_2, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_3,
                    new global::System.Memory<int>(buffer_3, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<int>(
                    field_4,
                    new global::System.Memory<int?>(buffer_4, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<byte>(
                    field_5,
                    new global::System.Memory<byte>(buffer_5, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<short>(
                    field_6,
                    new global::System.Memory<short>(buffer_6, 0, rowCount),
                    cancellationToken: cancellationToken);
                await groupReader.ReadAsync<float>(
                    field_7,
                    new global::System.Memory<float>(buffer_7, 0, rowCount),
                    cancellationToken: cancellationToken);

                for (int i = 0; i < rowCount; i++)
                {
                    results[currentOffset + i] = new ScalarMetric
                    {
                        RowId = buffer_0[i],
                        Flag = buffer_1[i],
                        NullableFlag = buffer_2[i],
                        StatusCode = (SampleDomain.Models.ProcessStatus)buffer_3[i],
                        OptionalStatus = buffer_4[i] is null ? (SampleDomain.Models.ProcessStatus?)null : (SampleDomain.Models.ProcessStatus)buffer_4[i]!,
                        TinyNum = buffer_5[i],
                        ShortNum = buffer_6[i],
                        FloatVal = buffer_7[i],
                    };
                }
                currentOffset += rowCount;
            }
        }
        finally
        {
            global::System.Buffers.ArrayPool<long>.Shared.Return(buffer_0, clearArray: false);
            global::System.Buffers.ArrayPool<bool>.Shared.Return(buffer_1, clearArray: false);
            global::System.Buffers.ArrayPool<bool?>.Shared.Return(buffer_2, clearArray: false);
            global::System.Buffers.ArrayPool<int>.Shared.Return(buffer_3, clearArray: false);
            global::System.Buffers.ArrayPool<int?>.Shared.Return(buffer_4, clearArray: false);
            global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer_5, clearArray: false);
            global::System.Buffers.ArrayPool<short>.Shared.Return(buffer_6, clearArray: false);
            global::System.Buffers.ArrayPool<float>.Shared.Return(buffer_7, clearArray: false);
        }

        return results;
    }

    /// <summary>
    /// Asynchronously streams <c>ScalarMetric</c> items from an in-memory byte buffer, row group by row group.
    /// </summary>
    public static async global::System.Collections.Generic.IAsyncEnumerable<ScalarMetric> ReadParquetStreamAsync(
        global::System.ReadOnlyMemory<byte> parquetBytes,
        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)
    {
        using var stream = CreateBufferStream(parquetBytes);
        await foreach (var item in ReadParquetStreamAsync(stream, options, cancellationToken))
        {
            yield return item;
        }
    }

    /// <summary>
    /// Wraps a byte buffer as a read-only stream, without copying where the buffer is array-backed.
    /// </summary>
    /// <remarks>
    /// Each call returns an independent stream over the same bytes, which is what makes the parallel
    /// reader possible: every worker gets its own cursor without copying the file.
    /// </remarks>
    private static global::System.IO.MemoryStream CreateBufferStream(global::System.ReadOnlyMemory<byte> parquetBytes)
    {
        return global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out var segment)
            ? new global::System.IO.MemoryStream(segment.Array!, segment.Offset, segment.Count, writable: false)
            : new global::System.IO.MemoryStream(parquetBytes.ToArray(), writable: false);
    }
}
