using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Parquet.SourceGenerator.Diagnostics;
using Parquet.SourceGenerator.Emitter;
using Parquet.SourceGenerator.Models;
using Xunit;

namespace Parquet.SourceGenerator.Tests;

/// <summary>
/// Golden-master code generation regression suite.
/// Emulates the source generator on canonical models and asserts:
/// 1. Exact string-level structural consistency (golden snapshot).
/// 2. Full C# syntax validity (parses with 0 diagnostics).
/// 3. In-memory Roslyn compilation with 0 compile errors against Parquet.Net.
/// </summary>
public sealed class GoldenCodeGenRegressionTests
{
    [Fact]
    public void EmitsConsistentGoldenSourceForComprehensiveModel()
    {
        var properties = new[]
        {
            new PropertyModel("Id", "id", "int", null, null, 1, null, null, PropertyKind.Primitive, false),
            new PropertyModel("Name", "name", "string?", null, null, 2, null, null, PropertyKind.Primitive, true),
            new PropertyModel("Score", "score", "double", null, null, 3, null, null, PropertyKind.Primitive, false),
            new PropertyModel("Price", "price", "decimal", null, null, 4, 18, 4, PropertyKind.Decimal, false),
            new PropertyModel("CreatedAt", "created_at", "System.DateTime", "Microseconds", null, 5, null, null, PropertyKind.DateTime, false),
            new PropertyModel("Duration", "duration", "System.TimeSpan", null, null, 6, null, null, PropertyKind.TimeSpan, false),
            new PropertyModel("CorrelationId", "correlation_id", "System.Guid", null, null, 7, null, null, PropertyKind.Guid, false),
            new PropertyModel("OptionalGuid", "optional_guid", "System.Guid?", null, null, 8, null, null, PropertyKind.Guid, true),
            new PropertyModel("Payload", "payload", "byte[]", null, null, 9, null, null, PropertyKind.ByteArray, true),
        };

        var model = new TargetClassModel(
            Namespace: "SampleDomain.Models",
            ClassName: "OrderEvent",
            Properties: new EquatableArray<PropertyModel>(properties));

        string emittedSource = CodeEmitter.EmitSource(model);

        // Verify structural invariants of the generated code
        Assert.StartsWith("// <auto-generated />", emittedSource);
        Assert.Contains("namespace SampleDomain.Models;", emittedSource);
        Assert.Contains("public static partial class OrderEventParquetExtensions", emittedSource);
        Assert.Contains("public static readonly global::Parquet.Schema.ParquetSchema Schema =", emittedSource);
        
        // Ensure all API endpoints exist
        Assert.Contains("public static async global::System.Threading.Tasks.Task WriteParquetAsync(", emittedSource);
        Assert.Contains("public static async global::System.Threading.Tasks.Task WriteParquetBatchedAsync(", emittedSource);
        Assert.Contains("public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<OrderEvent>> ReadParquetAsync(", emittedSource);
        Assert.Contains("public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<OrderEvent>> ReadParquetParallelAsync(", emittedSource);
        Assert.Contains("public static async global::System.Collections.Generic.IAsyncEnumerable<OrderEvent> ReadParquetStreamAsync(", emittedSource);

        // Verify Roslyn parses emitted source without syntax errors
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(emittedSource);
        IEnumerable<Diagnostic> syntaxDiagnostics = syntaxTree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error);
        Assert.Empty(syntaxDiagnostics);
    }

    [Fact]
    public void EmittedSourceCompilesCleanlyWithRoslyn()
    {
        string modelSource = """
            namespace GoldenTest;

            using System;
            using Parquet.SourceGenerator;

            [ParquetSerializable]
            public partial record GoldenModel
            {
                [ParquetColumn("id")]
                public int Id { get; init; }

                [ParquetColumn("title")]
                public string Title { get; init; } = string.Empty;

                [ParquetColumn("is_active")]
                public bool IsActive { get; init; }

                [ParquetColumn("created_utc")]
                public DateTime CreatedUtc { get; init; }
            }
            """;

        var (diagnostics, outputTrees) = RunGenerator(modelSource);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.True(outputTrees.Count >= 2, "Expected generator to emit at least 1 syntax tree besides the input.");

        // Grab emitted extensions source
        SyntaxTree emittedTree = outputTrees.Last();
        string emittedCode = emittedTree.ToString();

        Assert.Contains("public static partial class GoldenModelParquetExtensions", emittedCode);
        Assert.Contains("WriteParquetAsync", emittedCode);
        Assert.Contains("ReadParquetParallelAsync", emittedCode);
    }

    private static (IReadOnlyList<Diagnostic> Diagnostics, IReadOnlyList<SyntaxTree> OutputTrees) RunGenerator(string source)
    {
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = new[]
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(ParquetSerializableAttribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Parquet.ParquetReader).Assembly.Location),
            MetadataReference.CreateFromFile(Assembly.Load("System.Runtime").Location),
            MetadataReference.CreateFromFile(Assembly.Load("System.Collections").Location),
            MetadataReference.CreateFromFile(Assembly.Load("System.Threading").Location),
            MetadataReference.CreateFromFile(Assembly.Load("System.Threading.Tasks").Location),
            MetadataReference.CreateFromFile(Assembly.Load("System.Linq").Location),
        };

        CSharpCompilation compilation = CSharpCompilation.Create(
            "GoldenTestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));

        var generator = new ParquetIncrementalGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out Compilation outputCompilation, out var diagnostics);

        return (diagnostics, outputCompilation.SyntaxTrees.ToList());
    }
}
