using System;
using System.Text;
using Parquet.SourceGenerator.Emitter.Components;
using Parquet.SourceGenerator.Models;

namespace Parquet.SourceGenerator.Emitter;

/// <summary>
/// Emits high-performance C# extension classes targeting Parquet.Net v6 low-level primitives.
/// Features configurable ParquetSerializerOptions, IAsyncEnumerable streaming, compact 8-byte Int64 microsecond timestamp encoding,
/// parallel multi-row-group reading, zero-allocation Guid binary encoding, static pre-allocated DataFields,
/// O(1) index-check schema field resolution, ArrayPool buffer recycling, zero-copy ReadOnlyMemory overloads,
/// and Native AOT compatibility.
/// </summary>
public static class CodeEmitter
{
    /// <summary>
    /// Generates complete C# source code string for a given target model.
    /// </summary>
    public static string EmitSource(TargetClassModel model)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine(
            "#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8629"
        );
        builder.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }

        string extensionsClassName = $"{model.ClassName}ParquetExtensions";

        builder.AppendLine($"public static partial class {extensionsClassName}");
        builder.AppendLine("{");

        EmitSchema(builder, model);
        builder.AppendLine();

        EmitStaticFields(builder, model);
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            EmitResolveSchemaField(builder);
            builder.AppendLine();
        }

        EmitBuildFormatOptions(builder, model);
        builder.AppendLine();

        if (StringDeduplicatorComponent.HasStringProperties(model))
        {
            StringDeduplicatorComponent.EmitStringDeduplicator(builder);
            builder.AppendLine();
        }

        // Streaming row group writer — low level primitives, 100M+ scale, Native AOT compatible
        EmitWriteRowGroupAsync(builder, model);
        builder.AppendLine();

        // Primary write API — async (v6 requires async for writer creation)
        EmitWriteAsync(builder, model);
        builder.AppendLine();

        // Batched streaming write — splits IEnumerable into fixed-size row groups
        EmitWriteBatchedAsync(builder, model);
        builder.AppendLine();

        // IAsyncEnumerable streaming write
        EmitWriteAsyncEnumerable(builder, model);
        builder.AppendLine();

        // Read API — async (v6 low-level primitives)
        EmitReadAsync(builder, model);
        builder.AppendLine();

        // Direct array Read API — zero-copy array materialization
        EmitReadArrayAsync(builder, model);
        builder.AppendLine();

        // Parallel Read API — multi-core parallel object instantiation
        EmitReadParallelAsync(builder, model);
        builder.AppendLine();

        // Streaming Read API — IAsyncEnumerable streaming
        EmitReadStreamAsync(builder, model);
        builder.AppendLine();

        // Zero-copy ReadOnlyMemory overloads
        EmitReadMemoryOverloads(builder, model);

        builder.AppendLine("}");

        return builder.ToString();
    }

    // ──────────────────────────────────────────────────────────
    //  SCHEMA & STATIC FIELD CACHING
    // ──────────────────────────────────────────────────────────

    private static void EmitSchema(StringBuilder builder, TargetClassModel model)
    {
        SchemaComponent.EmitSchema(builder, model);
    }

    private static void EmitStaticFields(StringBuilder builder, TargetClassModel model)
    {
        SchemaComponent.EmitStaticFields(builder, model);
    }

    private static void EmitResolveSchemaField(StringBuilder builder)
    {
        SchemaComponent.EmitResolveSchemaField(builder, usePath: false);
    }

    // ──────────────────────────────────────────────────────────
    //  FORMAT OPTIONS & PRIMITIVES
    // ──────────────────────────────────────────────────────────

    private static void EmitBuildFormatOptions(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            "    /// Translates the generator's options into the Parquet.Net options the writer accepts."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            "    private static global::Parquet.ParquetOptions BuildFormatOptions(global::Parquet.SourceGenerator.ParquetSerializerOptions options)"
        );
        builder.AppendLine("    {");
        builder.AppendLine("        var formatOptions = new global::Parquet.ParquetOptions");
        builder.AppendLine("        {");
        builder.AppendLine("            CompressionMethod = options.CompressionMethod switch");
        builder.AppendLine("            {");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionMethod.None =>"
        );
        builder.AppendLine("                    global::Parquet.CompressionMethod.None,");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionMethod.Gzip =>"
        );
        builder.AppendLine("                    global::Parquet.CompressionMethod.Gzip,");
        builder.AppendLine("                // Parquet.Net spells this one in caps.");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionMethod.Lz4 =>"
        );
        builder.AppendLine("                    global::Parquet.CompressionMethod.LZ4,");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionMethod.Brotli =>"
        );
        builder.AppendLine("                    global::Parquet.CompressionMethod.Brotli,");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionMethod.Zstd =>"
        );
        builder.AppendLine("                    global::Parquet.CompressionMethod.Zstd,");
        builder.AppendLine("                _ => global::Parquet.CompressionMethod.Snappy,");
        builder.AppendLine("            },");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        if (options.CompressionLevel.HasValue)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            formatOptions.CompressionLevel = options.CompressionLevel.Value switch"
        );
        builder.AppendLine("            {");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionLevel.Optimal =>"
        );
        builder.AppendLine(
            "                    global::System.IO.Compression.CompressionLevel.Optimal,"
        );
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionLevel.Fastest =>"
        );
        builder.AppendLine(
            "                    global::System.IO.Compression.CompressionLevel.Fastest,"
        );
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetCompressionLevel.NoCompression =>"
        );
        builder.AppendLine(
            "                    global::System.IO.Compression.CompressionLevel.NoCompression,"
        );
        builder.AppendLine(
            "                _ => global::System.IO.Compression.CompressionLevel.SmallestSize,"
        );
        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (options.DictionaryEncodingThreshold.HasValue)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            formatOptions.DictionaryEncodingThreshold = options.DictionaryEncodingThreshold.Value;"
        );
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (options.DictionaryEncodingSampleSize.HasValue)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            formatOptions.DictionaryEncodingSampleSize = options.DictionaryEncodingSampleSize.Value;"
        );
        builder.AppendLine("        }");

        foreach (var prop in model.Properties)
        {
            if (prop.Encoding != ColumnEncoding.Default)
            {
                string hintValue = prop.Encoding switch
                {
                    ColumnEncoding.Dictionary => "global::Parquet.EncodingHint.Dictionary",
                    ColumnEncoding.DeltaBinaryPacked =>
                        "global::Parquet.EncodingHint.DeltaBinaryPacked",
                    ColumnEncoding.ByteSplitStream =>
                        "global::Parquet.EncodingHint.ByteSplitStream",
                    _ => "global::Parquet.EncodingHint.Default",
                };
                builder.AppendLine(
                    $"        formatOptions.ColumnEncodingHints[\"{prop.ParquetColumnName}\"] = {hintValue};"
                );
            }
        }

        builder.AppendLine();
        builder.AppendLine("        foreach (var kvp in options.ColumnEncodingHints)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            formatOptions.ColumnEncodingHints[kvp.Key] = kvp.Value switch"
        );
        builder.AppendLine("            {");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetColumnEncoding.Dictionary =>"
        );
        builder.AppendLine("                    global::Parquet.EncodingHint.Dictionary,");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetColumnEncoding.DeltaBinaryPacked =>"
        );
        builder.AppendLine("                    global::Parquet.EncodingHint.DeltaBinaryPacked,");
        builder.AppendLine(
            "                global::Parquet.SourceGenerator.ParquetColumnEncoding.ByteSplitStream =>"
        );
        builder.AppendLine("                    global::Parquet.EncodingHint.ByteSplitStream,");
        builder.AppendLine("                _ => global::Parquet.EncodingHint.Default,");
        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return formatOptions;");
        builder.AppendLine("    }");
    }

    private static string GetWritePrimitiveCall(
        PropertyModel prop,
        string fieldAccess,
        string bufName,
        int propIndex,
        string indent = "                "
    )
    {
        bool isString = prop.Kind == PropertyKind.Primitive && prop.TypeName.Contains("string");
        bool isByteArray = prop.Kind == PropertyKind.ByteArray;

        if (BufferPoolComponent.UsesWriteAllParts(prop))
        {
            string nonNullType = BufferPoolComponent.GetNonNullableBufferType(prop);
            return $"{indent}await groupWriter.WriteAllPartsAsync<{nonNullType}>(\n"
                + $"{indent}    {fieldAccess},\n"
                + $"{indent}    new global::System.ReadOnlyMemory<{nonNullType}>({bufName}, 0, nonNullCount_{propIndex}),\n"
                + $"{indent}    new global::System.ReadOnlyMemory<int>(defLevels_{propIndex}, 0, count),\n"
                + $"{indent}    null,\n"
                + $"{indent}    cancellationToken: cancellationToken);";
        }
        else if (isString)
        {
            string memType = prop.IsNullable
                ? "global::System.ReadOnlyMemory<char>?"
                : "global::System.ReadOnlyMemory<char>";
            return $"{indent}await groupWriter.WriteAsync<global::System.ReadOnlyMemory<char>>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{memType}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (isByteArray)
        {
            string memType = prop.IsNullable
                ? "global::System.ReadOnlyMemory<byte>?"
                : "global::System.ReadOnlyMemory<byte>";
            return $"{indent}await groupWriter.WriteAsync<global::System.ReadOnlyMemory<byte>>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{memType}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.Guid)
        {
            return $"{indent}await groupWriter.WriteAsync<global::System.Guid>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<global::System.Guid>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.Enum)
        {
            string underlying = prop.EnumUnderlyingTypeName ?? "int";
            return $"{indent}await groupWriter.WriteAsync<{underlying}>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{underlying}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.TimeSpan)
        {
            return $"{indent}await groupWriter.WriteAsync<int>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<int>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.TimeSpan)
        {
            string memType = prop.IsNullable ? "int?" : "int";
            return $"{indent}await groupWriter.WriteAsync<int>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{memType}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.TimeOnly)
        {
            string memType = prop.IsNullable ? "long?" : "long";
            return $"{indent}await groupWriter.WriteAsync<long>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{memType}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
        else
        {
            string structType = prop.TypeName.TrimEnd('?');
            return $"{indent}await groupWriter.WriteAsync<{structType}>(\n{indent}    {fieldAccess},\n{indent}    new global::System.ReadOnlyMemory<{structType}>({bufName}, 0, count),\n{indent}    cancellationToken: cancellationToken);";
        }
    }

    private static string GetReadPrimitiveCall(
        PropertyModel prop,
        string fieldAccess,
        string bufName,
        string indent = "                "
    )
    {
        bool isString = prop.Kind == PropertyKind.Primitive && prop.TypeName.Contains("string");
        bool isByteArray = prop.Kind == PropertyKind.ByteArray;

        if (isString)
        {
            return $"{indent}await groupReader.ReadAsync(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<string?>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (isByteArray)
        {
            return $"{indent}await groupReader.ReadAsync(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<byte[]?>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.Guid)
        {
            string memType = prop.IsNullable ? "global::System.Guid?" : "global::System.Guid";
            return $"{indent}await groupReader.ReadAsync<global::System.Guid>(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<{memType}>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.Enum)
        {
            string underlying = prop.EnumUnderlyingTypeName ?? "int";
            string memType = prop.IsNullable ? $"{underlying}?" : underlying;
            return $"{indent}await groupReader.ReadAsync<{underlying}>(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<{memType}>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.TimeSpan)
        {
            string memType = prop.IsNullable ? "int?" : "int";
            return $"{indent}await groupReader.ReadAsync<int>(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<{memType}>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else if (prop.Kind == PropertyKind.TimeOnly)
        {
            string memType = prop.IsNullable ? "long?" : "long";
            return $"{indent}await groupReader.ReadAsync<long>(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<{memType}>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
        else
        {
            string structType = prop.TypeName.TrimEnd('?');
            string memType = prop.IsNullable ? $"{structType}?" : structType;
            return $"{indent}await groupReader.ReadAsync<{structType}>(\n{indent}    {fieldAccess},\n{indent}    new global::System.Memory<{memType}>({bufName}, 0, rowCount),\n{indent}    cancellationToken: cancellationToken);";
        }
    }

    // ──────────────────────────────────────────────────────────
    //  WRITE METHODS
    // ──────────────────────────────────────────────────────────

    private static void EmitWriteRowGroupAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Writes a single row group chunk using Parquet.Net low-level primitives for maximum speed and Native AOT compatibility."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task WriteParquetRowGroupAsync("
        );
        builder.AppendLine($"        this global::Parquet.ParquetWriter writer,");
        builder.AppendLine(
            $"        global::System.Collections.Generic.IReadOnlyCollection<{model.ClassName}> chunk,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (writer == null) throw new global::System.ArgumentNullException(nameof(writer));"
        );
        builder.AppendLine(
            "        if (chunk == null) throw new global::System.ArgumentNullException(nameof(chunk));"
        );
        builder.AppendLine();
        builder.AppendLine("        int count = chunk.Count;");
        builder.AppendLine("        if (count == 0) return;");
        builder.AppendLine();

        BufferPoolComponent.EmitWriteRentals(builder, model, "count");

        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");

        if (PropertyMappingComponent.IsSingleFieldBlittableStruct(model))
        {
            string elemType = PropertyMappingComponent.GetSingleFieldBufferElementType(model);
            PropertyModel prop = model.Properties[0];
            builder.AppendLine(
                $"            if (chunk is global::System.Collections.Generic.List<{model.ClassName}> listItems)"
            );
            builder.AppendLine("            {");
            builder.AppendLine("#if NET6_0_OR_GREATER");
            builder.AppendLine(
                $"                if (global::System.Runtime.CompilerServices.Unsafe.SizeOf<{model.ClassName}>() == global::System.Runtime.CompilerServices.Unsafe.SizeOf<{elemType}>())"
            );
            builder.AppendLine("                {");
            builder.AppendLine(
                "                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(listItems);"
            );
            builder.AppendLine(
                $"                    global::System.Runtime.InteropServices.MemoryMarshal.Cast<{model.ClassName}, {elemType}>(span.Slice(0, count))"
            );
            builder.AppendLine("                        .CopyTo(buffer_0.AsSpan(0, count));");
            builder.AppendLine("                }");
            builder.AppendLine("                else");
            builder.AppendLine("                {");
            builder.AppendLine("                    for (int i = 0; i < count; i++)");
            builder.AppendLine("                    {");
            builder.AppendLine($"                        buffer_0[i] = listItems[i].{prop.Name};");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("#else");
            builder.AppendLine("                for (int i = 0; i < count; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var item = listItems[i];");
            EmitPropertyAssignments(builder, model, "buffer_", prefix: "                    ");
            builder.AppendLine("                }");
            builder.AppendLine("#endif");
            builder.AppendLine("            }");
            builder.AppendLine($"            else if (chunk is {model.ClassName}[] arrayItems)");
            builder.AppendLine("            {");
            builder.AppendLine("#if NET6_0_OR_GREATER");
            builder.AppendLine(
                $"                if (global::System.Runtime.CompilerServices.Unsafe.SizeOf<{model.ClassName}>() == global::System.Runtime.CompilerServices.Unsafe.SizeOf<{elemType}>())"
            );
            builder.AppendLine("                {");
            builder.AppendLine(
                $"                    global::System.Runtime.InteropServices.MemoryMarshal.Cast<{model.ClassName}, {elemType}>(arrayItems.AsSpan(0, count))"
            );
            builder.AppendLine("                        .CopyTo(buffer_0.AsSpan(0, count));");
            builder.AppendLine("                }");
            builder.AppendLine("                else");
            builder.AppendLine("                {");
            builder.AppendLine("                    for (int i = 0; i < count; i++)");
            builder.AppendLine("                    {");
            builder.AppendLine($"                        buffer_0[i] = arrayItems[i].{prop.Name};");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("#else");
            builder.AppendLine("                for (int i = 0; i < count; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    buffer_0[i] = arrayItems[i].{prop.Name};");
            builder.AppendLine("                }");
            builder.AppendLine("#endif");
            builder.AppendLine("            }");
            builder.AppendLine("            else");
            builder.AppendLine("            {");
            builder.AppendLine("                int idx = 0;");
            builder.AppendLine("                foreach (var item in chunk)");
            builder.AppendLine("                {");
            EmitPropertyAssignmentsIndexed(
                builder,
                model,
                "buffer_",
                prefix: "                    "
            );
            builder.AppendLine("                    idx++;");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
        }
        else
        {
            // List fast path
            builder.AppendLine(
                $"            if (chunk is global::System.Collections.Generic.List<{model.ClassName}> listItems)"
            );
            builder.AppendLine("            {");
            builder.AppendLine("#if NET6_0_OR_GREATER");
            builder.AppendLine("                void ExtractSpan()");
            builder.AppendLine("                {");
            builder.AppendLine(
                "                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(listItems);"
            );
            builder.AppendLine("                    for (int i = 0; i < count; i++)");
            builder.AppendLine("                    {");
            builder.AppendLine("                        var item = span[i];");
            EmitPropertyAssignments(builder, model, "buffer_", prefix: "                        ");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("                ExtractSpan();");
            builder.AppendLine("#else");
            builder.AppendLine("                for (int i = 0; i < count; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var item = listItems[i];");
            EmitPropertyAssignments(builder, model, "buffer_", prefix: "                    ");
            builder.AppendLine("                }");
            builder.AppendLine("#endif");
            builder.AppendLine("            }");

            // Array fast path
            builder.AppendLine($"            else if (chunk is {model.ClassName}[] arrayItems)");
            builder.AppendLine("            {");
            builder.AppendLine("                for (int i = 0; i < count; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var item = arrayItems[i];");
            EmitPropertyAssignments(builder, model, "buffer_", prefix: "                    ");
            builder.AppendLine("                }");
            builder.AppendLine("            }");

            // Enumerable fallback
            builder.AppendLine("            else");
            builder.AppendLine("            {");
            builder.AppendLine("                int idx = 0;");
            builder.AppendLine("                foreach (var item in chunk)");
            builder.AppendLine("                {");
            EmitPropertyAssignmentsIndexed(
                builder,
                model,
                "buffer_",
                prefix: "                    "
            );
            builder.AppendLine("                    idx++;");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
        }
        builder.AppendLine();

        // Write row group using static pre-allocated DataFields
        builder.AppendLine("            using (var groupWriter = writer.CreateRowGroup())");
        builder.AppendLine("            {");

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string fieldAccess = $"_field_{i}";
            builder.AppendLine(GetWritePrimitiveCall(prop, fieldAccess, $"buffer_{i}", i));
            BufferPoolComponent.EmitSingleWriteReturn(
                builder,
                prop,
                i,
                "buffer_",
                indent: "                "
            );
        }

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        finally");
        builder.AppendLine("        {");

        BufferPoolComponent.EmitWriteReturns(builder, model);

        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void EmitWriteAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously serializes all <c>{model.ClassName}</c> items using Parquet.Net low-level primitives."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task WriteParquetAsync("
        );
        builder.AppendLine(
            $"        this global::System.Collections.Generic.IReadOnlyCollection<{model.ClassName}> items,"
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (items == null) throw new global::System.ArgumentNullException(nameof(items));"
        );
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var writer = await global::Parquet.ParquetWriter.CreateAsync("
        );
        builder.AppendLine("            Schema,");
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine(
            "        await writer.WriteParquetRowGroupAsync(items, cancellationToken);"
        );
        builder.AppendLine("    }");
    }

    private static void EmitWriteBatchedAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Streams <c>{model.ClassName}</c> items into a Parquet file in fixed-size row group batches using low-level primitives."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task WriteParquetBatchedAsync("
        );
        builder.AppendLine(
            $"        this global::System.Collections.Generic.IEnumerable<{model.ClassName}> items,"
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine($"        int? rowGroupSize = null,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (items == null) throw new global::System.ArgumentNullException(nameof(items));"
        );
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        EmitRowGroupSizeResolution(builder);
        builder.AppendLine();
        builder.AppendLine(
            $"        if (items is global::System.Collections.Generic.IReadOnlyCollection<{model.ClassName}> col && col.Count <= targetChunkSize)"
        );
        builder.AppendLine("        {");
        builder.AppendLine(
            "            await using var singleWriter = await global::Parquet.ParquetWriter.CreateAsync("
        );
        builder.AppendLine("                Schema,");
        builder.AppendLine("                stream,");
        builder.AppendLine("                BuildFormatOptions(options),");
        builder.AppendLine("                cancellationToken: cancellationToken);");
        builder.AppendLine(
            "            await singleWriter.WriteParquetRowGroupAsync(col, cancellationToken);"
        );
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine(
            "        await using var writer = await global::Parquet.ParquetWriter.CreateAsync("
        );
        builder.AppendLine("            Schema,");
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine(
            $"        var buffer = new global::System.Collections.Generic.List<{model.ClassName}>(targetChunkSize);"
        );
        builder.AppendLine("        foreach (var item in items)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            buffer.Add(item);");
        builder.AppendLine("            if (buffer.Count == targetChunkSize)");
        builder.AppendLine("            {");
        builder.AppendLine(
            "                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);"
        );
        builder.AppendLine("                buffer.Clear();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        if (buffer.Count > 0)");
        builder.AppendLine(
            "            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);"
        );
        builder.AppendLine("    }");
    }

    private static void EmitWriteAsyncEnumerable(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Streams <c>{model.ClassName}</c> items asynchronously from an <c>IAsyncEnumerable&lt;{model.ClassName}&gt;</c> sequence into a Parquet file in fixed-size row group batches."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task WriteParquetAsync("
        );
        builder.AppendLine(
            $"        this global::System.Collections.Generic.IAsyncEnumerable<{model.ClassName}> items,"
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine($"        int? rowGroupSize = null,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (items == null) throw new global::System.ArgumentNullException(nameof(items));"
        );
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        EmitRowGroupSizeResolution(builder);
        builder.AppendLine();
        builder.AppendLine(
            "        await using var writer = await global::Parquet.ParquetWriter.CreateAsync("
        );
        builder.AppendLine("            Schema,");
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine(
            $"        var buffer = new global::System.Collections.Generic.List<{model.ClassName}>(targetChunkSize);"
        );
        builder.AppendLine("        await foreach (var item in items)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            buffer.Add(item);");
        builder.AppendLine("            if (buffer.Count == targetChunkSize)");
        builder.AppendLine("            {");
        builder.AppendLine(
            "                await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);"
        );
        builder.AppendLine("                buffer.Clear();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        if (buffer.Count > 0)");
        builder.AppendLine(
            "            await writer.WriteParquetRowGroupAsync(buffer, cancellationToken);"
        );
        builder.AppendLine("    }");
    }

    private static void EmitRowGroupSizeResolution(StringBuilder builder)
    {
        BatchValidationComponent.EmitRowGroupSizeResolution(builder, "targetChunkSize");
    }

    // ──────────────────────────────────────────────────────────
    //  READ METHODS
    // ──────────────────────────────────────────────────────────

    private static void EmitReadAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects using Parquet.Net low-level primitives."
        );
        builder.AppendLine(
            "    /// Fast O(1) index-check schema resolution and ArrayPool buffer recycling."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{model.ClassName}>> ReadParquetAsync("
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine(
            "        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);"
        );
        builder.AppendLine("#if NET8_0_OR_GREATER");
        builder.AppendLine(
            $"        var results = new global::System.Collections.Generic.List<{model.ClassName}>(totalRows);"
        );
        builder.AppendLine(
            "        global::System.Runtime.InteropServices.CollectionsMarshal.SetCount(results, totalRows);"
        );
        builder.AppendLine("#else");
        builder.AppendLine(
            $"        var results = new global::System.Collections.Generic.List<{model.ClassName}>(totalRows);"
        );
        builder.AppendLine("#endif");
        builder.AppendLine("        int currentOffset = 0;");
        builder.AppendLine();
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            builder.AppendLine(
                "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
            );
            for (int i = 0; i < model.Properties.Length; i++)
            {
                builder.AppendLine(
                    $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
                );
            }
            builder.AppendLine();
        }

        StringDeduplicatorComponent.EmitDeduplicatorDeclaration(builder, model);

        builder.AppendLine("        for (int r = 0; r < reader.RowGroupCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("            int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine();

        BufferPoolComponent.EmitRentals(builder, model, "rowCount", indent: "            ");

        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string fieldAccess = $"field_{i}";
            builder.AppendLine(GetReadPrimitiveCall(prop, fieldAccess, $"buffer_{i}"));
        }

        builder.AppendLine();
        if (PropertyMappingComponent.IsSingleFieldBlittableStruct(model))
        {
            string elemType = PropertyMappingComponent.GetSingleFieldBufferElementType(model);
            PropertyModel prop = model.Properties[0];
            builder.AppendLine("#if NET8_0_OR_GREATER");
            builder.AppendLine("                void PopulateSpan()");
            builder.AppendLine("                {");
            builder.AppendLine(
                "                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(results);"
            );
            builder.AppendLine(
                $"                    if (global::System.Runtime.CompilerServices.Unsafe.SizeOf<{model.ClassName}>() == global::System.Runtime.CompilerServices.Unsafe.SizeOf<{elemType}>())"
            );
            builder.AppendLine("                    {");
            builder.AppendLine(
                $"                        global::System.Runtime.InteropServices.MemoryMarshal.Cast<{elemType}, {model.ClassName}>(buffer_0.AsSpan(0, rowCount)).CopyTo(span.Slice(currentOffset, rowCount));"
            );
            builder.AppendLine("                    }");
            builder.AppendLine("                    else");
            builder.AppendLine("                    {");
            builder.AppendLine("                        for (int i = 0; i < rowCount; i++)");
            builder.AppendLine("                        {");
            builder.AppendLine(
                $"                            span[currentOffset + i] = new {model.ClassName} {{ {prop.Name} = buffer_0[i] }};"
            );
            builder.AppendLine("                        }");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("                PopulateSpan();");
            builder.AppendLine("#else");
            builder.AppendLine("                for (int i = 0; i < rowCount; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    results.Add(new {model.ClassName}");
            builder.AppendLine("                    {");
            builder.AppendLine($"                        {prop.Name} = buffer_0[i],");
            builder.AppendLine("                    });");
            builder.AppendLine("                }");
            builder.AppendLine("#endif");
        }
        else
        {
            builder.AppendLine("#if NET8_0_OR_GREATER");
            builder.AppendLine("                void PopulateSpan()");
            builder.AppendLine("                {");
            builder.AppendLine(
                "                    var span = global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(results);"
            );
            builder.AppendLine("                    for (int i = 0; i < rowCount; i++)");
            builder.AppendLine("                    {");
            builder.AppendLine(
                $"                        span[currentOffset + i] = new {model.ClassName}"
            );
            builder.AppendLine("                        {");

            for (int i = 0; i < model.Properties.Length; i++)
            {
                PropertyModel prop = model.Properties[i];
                string readExpr = GetReadExpression(prop, $"buffer_{i}[i]");
                builder.AppendLine($"                            {prop.Name} = {readExpr},");
            }

            builder.AppendLine("                        };");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("                PopulateSpan();");
            builder.AppendLine("#else");
            builder.AppendLine("                for (int i = 0; i < rowCount; i++)");
            builder.AppendLine("                {");
            builder.AppendLine($"                    results.Add(new {model.ClassName}");
            builder.AppendLine("                    {");

            for (int i = 0; i < model.Properties.Length; i++)
            {
                PropertyModel prop = model.Properties[i];
                string readExpr = GetReadExpression(prop, $"buffer_{i}[i]");
                builder.AppendLine($"                        {prop.Name} = {readExpr},");
            }

            builder.AppendLine("                    });");
            builder.AppendLine("                }");
            builder.AppendLine("#endif");
        }
        builder.AppendLine("                currentOffset += rowCount;");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");

        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return results;");
        builder.AppendLine("    }");
    }

    private static void EmitReadArrayAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects directly into an array using Parquet.Net low-level primitives."
        );
        builder.AppendLine(
            "    /// Eliminates List wrapper allocations for zero-copy array materialization."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<{model.ClassName}[]> ReadParquetArrayAsync("
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine(
            "        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);"
        );
        builder.AppendLine($"        var results = new {model.ClassName}[totalRows];");
        builder.AppendLine("        int currentOffset = 0;");
        builder.AppendLine();
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            builder.AppendLine(
                "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
            );
            for (int i = 0; i < model.Properties.Length; i++)
            {
                builder.AppendLine(
                    $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
                );
            }
            builder.AppendLine();
        }

        StringDeduplicatorComponent.EmitDeduplicatorDeclaration(builder, model);

        builder.AppendLine("        for (int r = 0; r < reader.RowGroupCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("            int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine();

        BufferPoolComponent.EmitRentals(builder, model, "rowCount", indent: "            ");

        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string fieldAccess = $"field_{i}";
            builder.AppendLine(GetReadPrimitiveCall(prop, fieldAccess, $"buffer_{i}"));
        }

        builder.AppendLine();
        PropertyMappingComponent.EmitArrayMaterialization(
            builder,
            model,
            "results",
            "currentOffset",
            indent: "                "
        );
        builder.AppendLine("                currentOffset += rowCount;");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");

        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return results;");
        builder.AppendLine("    }");
    }

    private static void EmitReadStreamAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously streams <c>{model.ClassName}</c> items row-group by row-group as an <see cref=\"global::System.Collections.Generic.IAsyncEnumerable{{T}}\"/>."
        );
        builder.AppendLine(
            "    /// Memory usage is bounded by a single row group rather than the whole file."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Collections.Generic.IAsyncEnumerable<{model.ClassName}> ReadParquetStreamAsync("
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            builder.AppendLine(
                "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
            );
            for (int i = 0; i < model.Properties.Length; i++)
            {
                builder.AppendLine(
                    $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
                );
            }
            builder.AppendLine();
        }

        StringDeduplicatorComponent.EmitDeduplicatorDeclaration(builder, model);

        builder.AppendLine("        for (int r = 0; r < reader.RowGroupCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("            int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine();

        BufferPoolComponent.EmitRentals(builder, model, "rowCount", indent: "            ");

        builder.AppendLine("            try");
        builder.AppendLine("            {");

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string fieldAccess = $"field_{i}";
            builder.AppendLine(GetReadPrimitiveCall(prop, fieldAccess, $"buffer_{i}"));
        }

        builder.AppendLine();
        builder.AppendLine("                for (int i = 0; i < rowCount; i++)");
        builder.AppendLine("                {");
        builder.AppendLine($"                    yield return new {model.ClassName}");
        builder.AppendLine("                    {");

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string readExpr = GetReadExpression(prop, $"buffer_{i}[i]");
            builder.AppendLine($"                        {prop.Name} = {readExpr},");
        }

        builder.AppendLine("                    };");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");

        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void EmitReadMemoryOverloads(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects directly from an in-memory byte buffer with zero buffer allocation."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{model.ClassName}>> ReadParquetAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var results = await ReadBufferSequentialArrayAsync(parquetBytes, options, cancellationToken);"
        );
        builder.AppendLine(
            $"        return new global::System.Collections.Generic.List<{model.ClassName}>(results);"
        );
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects directly from an in-memory byte buffer into an array with zero buffer allocation."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<{model.ClassName}[]> ReadParquetArrayAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        return await ReadBufferSequentialArrayAsync(parquetBytes, options, cancellationToken);"
        );
        builder.AppendLine("    }");
        builder.AppendLine();

        EmitReadParallelBufferAsync(builder, model);
        builder.AppendLine();

        EmitReadBufferSequentialArrayAsync(builder, model);
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously streams <c>{model.ClassName}</c> items from an in-memory byte buffer, row group by row group."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Collections.Generic.IAsyncEnumerable<{model.ClassName}> ReadParquetStreamAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine("        using var stream = CreateBufferStream(parquetBytes);");
        builder.AppendLine(
            "        await foreach (var item in ReadParquetStreamAsync(stream, options, cancellationToken))"
        );
        builder.AppendLine("        {");
        builder.AppendLine("            yield return item;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            "    /// Wraps a byte buffer as a read-only stream, without copying where the buffer is array-backed."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <remarks>");
        builder.AppendLine(
            "    /// Each call returns an independent stream over the same bytes, which is what makes the parallel"
        );
        builder.AppendLine(
            "    /// reader possible: every worker gets its own cursor without copying the file."
        );
        builder.AppendLine("    /// </remarks>");
        builder.AppendLine(
            "    private static global::System.IO.MemoryStream CreateBufferStream(global::System.ReadOnlyMemory<byte> parquetBytes)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        return global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out var segment)"
        );
        builder.AppendLine(
            "            ? new global::System.IO.MemoryStream(segment.Array!, segment.Offset, segment.Count, writable: false)"
        );
        builder.AppendLine(
            "            : new global::System.IO.MemoryStream(parquetBytes.ToArray(), writable: false);"
        );
        builder.AppendLine("    }");
    }

    private static void EmitReadBufferSequentialArrayAsync(
        StringBuilder builder,
        TargetClassModel model
    )
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Dedicated sequential reader over an in-memory buffer without threadpool hops or stream wrapping overhead."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    private static async global::System.Threading.Tasks.Task<{model.ClassName}[]> ReadBufferSequentialArrayAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine("        using var stream = CreateBufferStream(parquetBytes);");
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine("        int rowGroupCount = reader.RowGroupCount;");
        builder.AppendLine(
            $"        if (rowGroupCount == 0) return global::System.Array.Empty<{model.ClassName}>();"
        );
        builder.AppendLine();
        RowGroupLayoutComponent.EmitLayoutProbe(
            builder,
            "reader",
            "totalRows",
            "maxRowCount",
            "rowGroupCount",
            declareRowGroupCount: false
        );
        builder.AppendLine();
        builder.AppendLine($"        var results = new {model.ClassName}[totalRows];");
        builder.AppendLine("        int currentOffset = 0;");
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine(
            "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
        );
        builder.AppendLine();

        for (int i = 0; i < model.Properties.Length; i++)
        {
            builder.AppendLine(
                $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
            );
        }

        builder.AppendLine();
        BufferPoolComponent.EmitRentals(builder, model, "maxRowCount");
        builder.AppendLine();

        StringDeduplicatorComponent.EmitDeduplicatorDeclaration(builder, model);

        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            for (int r = 0; r < rowGroupCount; r++)");
        builder.AppendLine("            {");
        builder.AppendLine("                cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("                using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("                int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine("                if (rowCount == 0) continue;");
        builder.AppendLine();

        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            builder.AppendLine(GetReadPrimitiveCall(prop, $"field_{i}", $"buffer_{i}"));
        }

        builder.AppendLine();
        PropertyMappingComponent.EmitArrayMaterialization(
            builder,
            model,
            "results",
            "currentOffset",
            indent: "                "
        );
        builder.AppendLine("                currentOffset += rowCount;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        finally");
        builder.AppendLine("        {");

        BufferPoolComponent.EmitReturns(builder, model);

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return results;");
        builder.AppendLine("    }");
    }

    // ──────────────────────────────────────────────────────────
    //  PARALLEL READ METHODS
    // ──────────────────────────────────────────────────────────

    private static void EmitReadParallelAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects from a Parquet stream directly into an array."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <remarks>");
        builder.AppendLine("    /// <para>");
        builder.AppendLine(
            "    /// This overload reads row groups sequentially. A single <c>ParquetReader</c> over one"
        );
        builder.AppendLine(
            "    /// <c>Stream</c> cannot be read concurrently — the reader seeks within the stream, so overlapping"
        );
        builder.AppendLine(
            "    /// row-group reads corrupt each other — and an arbitrary <c>Stream</c> cannot be handed to more"
        );
        builder.AppendLine("    /// than one reader.");
        builder.AppendLine("    /// </para>");
        builder.AppendLine("    /// <para>");
        builder.AppendLine(
            "    /// For genuine decode parallelism use the <c>ReadOnlyMemory&lt;byte&gt;</c> overload, which gives"
        );
        builder.AppendLine(
            "    /// every worker its own reader over its own view of the same bytes."
        );
        builder.AppendLine("    /// </para>");
        builder.AppendLine("    /// </remarks>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<{model.ClassName}[]> ReadParquetParallelArrayAsync("
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine($"        int maxDegreeOfParallelism = -1,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            "        if (stream == null) throw new global::System.ArgumentNullException(nameof(stream));"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("            stream,");
        builder.AppendLine("            BuildFormatOptions(options),");
        builder.AppendLine("            cancellationToken: cancellationToken);");
        builder.AppendLine("        int rgCount = reader.RowGroupCount;");
        builder.AppendLine(
            $"        if (rgCount == 0) return global::System.Array.Empty<{model.ClassName}>();"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        int totalRows = (int)global::System.Linq.Enumerable.Sum(reader.RowGroups, rg => rg.RowCount);"
        );
        builder.AppendLine($"        var resultArray = new {model.ClassName}[totalRows];");
        builder.AppendLine("        var rowOffsets = new int[rgCount];");
        builder.AppendLine("        int currentOffset = 0;");
        builder.AppendLine("        for (int r = 0; r < rgCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            rowOffsets[r] = currentOffset;");
        builder.AppendLine("            currentOffset += (int)reader.RowGroups[r].RowCount;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();
        if (model.Properties.Length > 0)
        {
            builder.AppendLine(
                "        global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
            );
            for (int i = 0; i < model.Properties.Length; i++)
            {
                builder.AppendLine(
                    $"        var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
                );
            }
            builder.AppendLine();
        }

        StringDeduplicatorComponent.EmitDeduplicatorDeclaration(builder, model);

        builder.AppendLine("        for (int r = 0; r < rgCount; r++)");
        builder.AppendLine("        {");
        builder.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("            using var groupReader = reader.OpenRowGroupReader(r);");
        builder.AppendLine("            int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine("            int startIdx = rowOffsets[r];");
        builder.AppendLine();
        BufferPoolComponent.EmitRentals(builder, model, "rowCount", indent: "            ");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            string fieldAccess = $"field_{i}";
            builder.AppendLine(GetReadPrimitiveCall(prop, fieldAccess, $"buffer_{i}"));
        }
        builder.AppendLine();
        PropertyMappingComponent.EmitArrayMaterialization(
            builder,
            model,
            "resultArray",
            "startIdx",
            indent: "                "
        );
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return resultArray;");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects from a Parquet stream, materialising"
        );
        builder.AppendLine(
            "    /// into a single pre-sized list indexed by row-group offset rather than growing a list."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{model.ClassName}>> ReadParquetParallelAsync("
        );
        builder.AppendLine($"        global::System.IO.Stream stream,");
        builder.AppendLine($"        int maxDegreeOfParallelism = -1,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var resultArray = await ReadParquetParallelArrayAsync(stream, maxDegreeOfParallelism, options, cancellationToken);"
        );
        builder.AppendLine(
            $"        return new global::System.Collections.Generic.List<{model.ClassName}>(resultArray);"
        );
        builder.AppendLine("    }");
    }

    private static void EmitReadParallelBufferAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects from an in-memory byte buffer into an array,"
        );
        builder.AppendLine(
            "    /// decoding row groups across multiple workers with zero list wrapper allocation."
        );
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<{model.ClassName}[]> ReadParquetParallelArrayAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine($"        int maxDegreeOfParallelism = -1,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine(
            "        options ??= global::Parquet.SourceGenerator.ParquetSerializerOptions.Default;"
        );
        builder.AppendLine("        var formatOptions = BuildFormatOptions(options);");
        builder.AppendLine();
        builder.AppendLine(
            "        var sourceBytes = global::System.Runtime.InteropServices.MemoryMarshal.TryGetArray(parquetBytes, out _)"
        );
        builder.AppendLine("            ? parquetBytes");
        builder.AppendLine(
            "            : new global::System.ReadOnlyMemory<byte>(parquetBytes.ToArray());"
        );
        builder.AppendLine();
        builder.AppendLine("        int rowGroupCount;");
        builder.AppendLine("        int totalRows;");
        builder.AppendLine("        int maxRowGroupSize;");
        builder.AppendLine("        int[] rowOffsets;");
        builder.AppendLine("        using (var probeStream = CreateBufferStream(sourceBytes))");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            await using var probe = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("                probeStream,");
        builder.AppendLine("                formatOptions,");
        builder.AppendLine("                cancellationToken: cancellationToken);");
        RowGroupLayoutComponent.EmitIndexedLayoutProbe(
            builder,
            "probe",
            "rowGroupCount",
            "rowOffsets",
            "totalRows",
            "maxRowGroupSize",
            declareVariables: false,
            indent: "            "
        );
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine(
            $"        if (rowGroupCount == 0) return global::System.Array.Empty<{model.ClassName}>();"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        // Small row count or single row group fast path: drop to sequential reader"
        );
        builder.AppendLine("        if (rowGroupCount <= 1 || totalRows <= 10_000)");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            return await ReadBufferSequentialArrayAsync(sourceBytes, options, cancellationToken);"
        );
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        var resultArray = new {model.ClassName}[totalRows];");
        builder.AppendLine(
            "        using var linkedCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);"
        );
        builder.AppendLine("        var workerToken = linkedCts.Token;");
        builder.AppendLine("        var cursor = new int[1];");
        builder.AppendLine();
        builder.AppendLine("        int requested = maxDegreeOfParallelism > 0");
        builder.AppendLine("            ? maxDegreeOfParallelism");
        builder.AppendLine(
            "            : (options.MaxDegreeOfParallelism > 0 ? options.MaxDegreeOfParallelism : global::System.Environment.ProcessorCount);"
        );
        builder.AppendLine(
            "        int workerCount = global::System.Math.Max(1, global::System.Math.Min(requested, rowGroupCount));"
        );
        builder.AppendLine();
        builder.AppendLine("        if (workerCount == 1)");
        builder.AppendLine("        {");
        builder.AppendLine("            await ReadRowGroupsIntoAsync(sourceBytes,");
        builder.AppendLine("                formatOptions,");
        builder.AppendLine("                resultArray,");
        builder.AppendLine("                rowOffsets,");
        builder.AppendLine("                cursor,");
        builder.AppendLine("                rowGroupCount,");
        builder.AppendLine("                maxRowGroupSize,");
        if (StringDeduplicatorComponent.HasStringProperties(model))
        {
            builder.AppendLine("                options.DeduplicateStrings,");
        }
        builder.AppendLine("                linkedCts,");
        builder.AppendLine("                workerToken);");
        builder.AppendLine("        }");
        builder.AppendLine("        else");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            var workers = new global::System.Threading.Tasks.Task[workerCount];"
        );
        builder.AppendLine("            for (int w = 0; w < workerCount; w++)");
        builder.AppendLine("            {");
        builder.AppendLine("                workers[w] = global::System.Threading.Tasks.Task.Run(");
        builder.AppendLine("                    () => ReadRowGroupsIntoAsync(sourceBytes,");
        builder.AppendLine("                        formatOptions,");
        builder.AppendLine("                        resultArray,");
        builder.AppendLine("                        rowOffsets,");
        builder.AppendLine("                        cursor,");
        builder.AppendLine("                        rowGroupCount,");
        builder.AppendLine("                        maxRowGroupSize,");
        if (StringDeduplicatorComponent.HasStringProperties(model))
        {
            builder.AppendLine("                        options.DeduplicateStrings,");
        }
        builder.AppendLine("                        linkedCts,");
        builder.AppendLine("                        workerToken),");
        builder.AppendLine("                    workerToken);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine(
            "                await global::System.Threading.Tasks.Task.WhenAll(workers);"
        );
        builder.AppendLine("            }");
        builder.AppendLine("            catch");
        builder.AppendLine("            {");
        builder.AppendLine("                linkedCts.Cancel();");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return resultArray;");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            $"    /// Asynchronously deserializes all <c>{model.ClassName}</c> objects from an in-memory byte buffer,"
        );
        builder.AppendLine("    /// decoding row groups across multiple workers.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<{model.ClassName}>> ReadParquetParallelAsync("
        );
        builder.AppendLine($"        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine($"        int maxDegreeOfParallelism = -1,");
        builder.AppendLine(
            $"        global::Parquet.SourceGenerator.ParquetSerializerOptions? options = null,"
        );
        builder.AppendLine(
            $"        global::System.Threading.CancellationToken cancellationToken = default)"
        );
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var resultArray = await ReadParquetParallelArrayAsync(parquetBytes, maxDegreeOfParallelism, options, cancellationToken);"
        );
        builder.AppendLine(
            $"        return new global::System.Collections.Generic.List<{model.ClassName}>(resultArray);"
        );
        builder.AppendLine("    }");
        builder.AppendLine();

        EmitReadRowGroupsIntoAsync(builder, model);
    }

    private static void EmitReadRowGroupsIntoAsync(StringBuilder builder, TargetClassModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine(
            "    /// One parallel-read worker: opens its own reader over the shared buffer and materialises every"
        );
        builder.AppendLine("    /// row group it manages to claim.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <remarks>");
        builder.AppendLine(
            "    /// Workers write into disjoint index ranges of <paramref name=\"target\"/> — a row group's rows"
        );
        builder.AppendLine(
            "    /// start at its precomputed offset — so no synchronisation is needed beyond claiming the group."
        );
        builder.AppendLine("    /// </remarks>");
        builder.AppendLine(
            "    private static async global::System.Threading.Tasks.Task ReadRowGroupsIntoAsync("
        );
        builder.AppendLine("        global::System.ReadOnlyMemory<byte> parquetBytes,");
        builder.AppendLine("        global::Parquet.ParquetOptions formatOptions,");
        builder.AppendLine($"        {model.ClassName}[] target,");
        builder.AppendLine("        int[] rowOffsets,");
        builder.AppendLine("        int[] cursor,");
        builder.AppendLine("        int rowGroupCount,");
        builder.AppendLine("        int maxRowGroupSize,");
        if (StringDeduplicatorComponent.HasStringProperties(model))
        {
            builder.AppendLine("        bool deduplicateStrings,");
        }
        builder.AppendLine("        global::System.Threading.CancellationTokenSource linkedCts,");
        builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            using var stream = CreateBufferStream(parquetBytes);");
        builder.AppendLine(
            "            await using var reader = await global::Parquet.ParquetReader.CreateAsync("
        );
        builder.AppendLine("                stream,");
        builder.AppendLine("                formatOptions,");
        builder.AppendLine("                cancellationToken: cancellationToken);");
        builder.AppendLine();
        builder.AppendLine("            var fileFields = reader.Schema.DataFields;");
        builder.AppendLine();

        if (model.Properties.Length > 0)
        {
            builder.AppendLine(
                "            global::System.Collections.Generic.Dictionary<string, global::Parquet.Schema.DataField>? fieldsByName = null;"
            );
            for (int i = 0; i < model.Properties.Length; i++)
            {
                builder.AppendLine(
                    $"            var field_{i} = ResolveSchemaField(fileFields, {i}, _field_{i}, ref fieldsByName);"
                );
            }
            builder.AppendLine();
        }

        BufferPoolComponent.EmitRentals(builder, model, "maxRowGroupSize", indent: "            ");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        if (StringDeduplicatorComponent.HasStringProperties(model))
        {
            builder.AppendLine(
                "                using var stringDeduplicator = new StringDeduplicator(512);"
            );
            builder.AppendLine();
        }
        builder.AppendLine("                while (true)");
        builder.AppendLine("                {");
        builder.AppendLine(
            "                    int r = global::System.Threading.Interlocked.Increment(ref cursor[0]) - 1;"
        );
        builder.AppendLine("                    if (r >= rowGroupCount) break;");
        builder.AppendLine();
        builder.AppendLine("                    cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine(
            "                    using var groupReader = reader.OpenRowGroupReader(r);"
        );
        builder.AppendLine("                    int rowCount = (int)groupReader.RowCount;");
        builder.AppendLine("                    int startIdx = rowOffsets[r];");
        builder.AppendLine();
        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            builder.AppendLine(
                GetReadPrimitiveCall(
                    prop,
                    $"field_{i}",
                    $"buffer_{i}",
                    indent: "                    "
                )
            );
        }
        builder.AppendLine();
        PropertyMappingComponent.EmitArrayMaterialization(
            builder,
            model,
            "target",
            "startIdx",
            indent: "                    "
        );
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        BufferPoolComponent.EmitReturns(builder, model, indent: "                ");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        catch");
        builder.AppendLine("        {");
        builder.AppendLine("            linkedCts.Cancel();");
        builder.AppendLine("            throw;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    // ──────────────────────────────────────────────────────────
    //  TYPE MAPPING & HELPERS
    // ──────────────────────────────────────────────────────────

    private static void EmitPropertyAssignments(
        StringBuilder builder,
        TargetClassModel model,
        string bufPrefix,
        string prefix
    )
    {
        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            if (BufferPoolComponent.UsesWriteAllParts(prop))
            {
                string valVar = $"val_{i}";
                builder.AppendLine($"{prefix}var {valVar} = item.{prop.Name};");
                builder.AppendLine($"{prefix}if ({valVar}.HasValue)");
                builder.AppendLine($"{prefix}{{");
                string nonNullExpr = prop.Kind switch
                {
                    PropertyKind.Enum => $"({prop.EnumUnderlyingTypeName ?? "int"}){valVar}.Value",
                    PropertyKind.TimeSpan => $"checked((int){valVar}.Value.TotalMilliseconds)",
                    PropertyKind.TimeOnly => $"{valVar}.Value.Ticks / 10L",
                    _ => $"{valVar}.Value",
                };
                builder.AppendLine(
                    $"{prefix}    {bufPrefix}{i}[nonNullCount_{i}++] = {nonNullExpr};"
                );
                builder.AppendLine($"{prefix}    defLevels_{i}[i] = 1;");
                builder.AppendLine($"{prefix}}}");
                builder.AppendLine($"{prefix}else");
                builder.AppendLine($"{prefix}{{");
                builder.AppendLine($"{prefix}    defLevels_{i}[i] = 0;");
                builder.AppendLine($"{prefix}}}");
            }
            else
            {
                string writeExpr = GetWriteExpression(prop, $"item.{prop.Name}");
                builder.AppendLine($"{prefix}{bufPrefix}{i}[i] = {writeExpr};");
            }
        }
    }

    private static void EmitPropertyAssignmentsIndexed(
        StringBuilder builder,
        TargetClassModel model,
        string bufPrefix,
        string prefix
    )
    {
        for (int i = 0; i < model.Properties.Length; i++)
        {
            PropertyModel prop = model.Properties[i];
            if (BufferPoolComponent.UsesWriteAllParts(prop))
            {
                string valVar = $"val_{i}";
                builder.AppendLine($"{prefix}var {valVar} = item.{prop.Name};");
                builder.AppendLine($"{prefix}if ({valVar}.HasValue)");
                builder.AppendLine($"{prefix}{{");
                string nonNullExpr = prop.Kind switch
                {
                    PropertyKind.Enum => $"({prop.EnumUnderlyingTypeName ?? "int"}){valVar}.Value",
                    PropertyKind.TimeSpan => $"checked((int){valVar}.Value.TotalMilliseconds)",
                    PropertyKind.TimeOnly => $"{valVar}.Value.Ticks / 10L",
                    _ => $"{valVar}.Value",
                };
                builder.AppendLine(
                    $"{prefix}    {bufPrefix}{i}[nonNullCount_{i}++] = {nonNullExpr};"
                );
                builder.AppendLine($"{prefix}    defLevels_{i}[idx] = 1;");
                builder.AppendLine($"{prefix}}}");
                builder.AppendLine($"{prefix}else");
                builder.AppendLine($"{prefix}{{");
                builder.AppendLine($"{prefix}    defLevels_{i}[idx] = 0;");
                builder.AppendLine($"{prefix}}}");
            }
            else
            {
                string writeExpr = GetWriteExpression(prop, $"item.{prop.Name}");
                builder.AppendLine($"{prefix}{bufPrefix}{i}[idx] = {writeExpr};");
            }
        }
    }

    private static string GetBufferElementType(PropertyModel prop) =>
        BufferPoolComponent.GetBufferElementType(prop);

    private static bool IsReferenceTypeBuffer(PropertyModel prop) =>
        BufferPoolComponent.IsReferenceTypeBuffer(prop);

    private static string GetWriteExpression(PropertyModel prop, string valueExpr) =>
        PropertyMappingComponent.GetWriteExpression(prop, valueExpr);

    private static string GetReadExpression(PropertyModel prop, string valueExpr) =>
        PropertyMappingComponent.GetReadExpression(prop, valueExpr);

    private static string BoolLiteral(bool value) => SchemaComponent.BoolLiteral(value);
}
